apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
    name: rekrutteringsbistand-stilling
    namespace: toi
    labels:
        team: toi
spec:
    # prettier-ignore
    image: {{ image }}
    port: 8080
    replicas:
        min: 2
        max: 3
        cpuThresholdPercentage: 50
    prometheus:
        enabled: false
        path: /metrics
    liveness:
        initialDelay: 10
        path: /rekrutteringsbistand-stilling/internal/isAlive
    readiness:
        initialDelay: 10
        path: /rekrutteringsbistand-stilling/internal/isReady
    resources:
        limits:
            cpu: 500m
            memory: 256Mi
        requests:
            cpu: 200m
            memory: 128Mi
    ingresses:
        - https://rekrutteringsbistand.intern.nav.no/rekrutteringsbistand-stilling
    env:
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/ssl/ca-bundle.pem
