import { Arbeidsgiverforslag } from '../opprett-ny-stilling/VelgArbeidsgiver';

const devVirksomheter: Arbeidsgiverforslag[] = [
    {
        orgnr: '313169642',
        name: 'ELASTISK INTELLIGENT TIGER AS',
        location: {
            address: 'Norheimtunet 22',
            postalCode: '5542',
            city: 'KARMSUND',
            municipal: 'KARMØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '312572095',
        name: 'UGJENNOMSIKTIG RUND TIGER AS',
        location: {
            address: 'Trondheimsveien 79',
            postalCode: '2019',
            city: 'SKEDSMOKORSET',
            municipal: 'LILLESTRØM',
            country: 'Norge',
        },
    },
    {
        orgnr: '310214450',
        name: 'VISSEN FJONG TIGER AS',
        location: {
            address: 'Sankthanshaugen 2',
            postalCode: '6514',
            city: 'KRISTIANSUND N',
            municipal: 'KRISTIANSUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '214274442',
        name: 'FIKTIV RETTFERDIG TIGER AS',
        location: {
            address: 'Gullestadvegen 8',
            postalCode: '4480',
            city: 'KVINESDAL',
            municipal: 'KVINESDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '313132714',
        name: 'PÅLITELIG KULTURELL APE',
        location: {
            address: 'Fredriksborgveien 41A',
            postalCode: '0286',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '312664917',
        name: 'ELEKTRONISK USYMMETRISK TIGER AS',
        location: {
            address: 'Malangsveien 2978',
            postalCode: '9056',
            city: 'MORTENHALS',
            municipal: 'BALSFJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '313050718',
        name: 'UNDERDANIG VAKLENDE TIGER AS',
        location: {
            address: 'Moslings vei 41',
            postalCode: '8514',
            city: 'NARVIK',
            municipal: 'NARVIK',
            country: 'Norge',
        },
    },
    {
        orgnr: '310716804',
        name: 'SUNN SELVHJULPEN TIGER AS',
        location: {
            address: 'Sandeveien 32',
            postalCode: '3150',
            city: 'TOLVSRØD',
            municipal: 'TØNSBERG',
            country: 'Norge',
        },
    },
    {
        orgnr: '314060539',
        name: 'URIMELIG SKÅNSOM TIGER AS',
        location: {
            address: 'Geitstadvegen 120',
            postalCode: '3870',
            city: 'FYRESDAL',
            municipal: 'FYRESDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '213889672',
        name: 'EMPIRISK UROKKELIG TIGER AS',
        location: {
            address: 'Rørkiltoppen 43',
            postalCode: '4904',
            city: 'TVEDESTRAND',
            municipal: 'TVEDESTRAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '313234835',
        name: 'LIVLIG ALFABETISK TIGER AS',
        location: {
            address: 'v/ Moderne Personlig Æresdoktor',
            postalCode: '1364',
            city: 'FORNEBU',
            municipal: 'BÆRUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '312265575',
        name: 'UNGT FREIDIG TIGER AS',
        location: {
            address: 'Nerbøvegen 112',
            postalCode: '6480',
            city: 'AUKRA',
            municipal: 'AUKRA',
            country: 'Norge',
        },
    },
    {
        orgnr: '314283252',
        name: 'SOLID AKROBATISK TIGER AS',
        location: {
            address: 'c/o Diskret Klutkreps',
            postalCode: '1363',
            city: 'HØVIK',
            municipal: 'BÆRUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '313120880',
        name: 'RIK BARMHJERTIG TIGER AS',
        location: {
            address: 'Konvallveien 10',
            postalCode: '0855',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314282892',
        name: 'SKAMFULL RUSTEN TIGER AS',
        location: {
            address: 'Bjørkebakken 8A',
            postalCode: '3340',
            city: 'ÅMOT',
            municipal: 'MODUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '312186403',
        name: 'MOMENTAN FINTFØLENDE PIGGSVIN',
        location: {
            address: 'Budorvegen 890',
            postalCode: '2340',
            city: 'LØTEN',
            municipal: 'LØTEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '313197727',
        name: 'KOMFORTABEL ENTUSIASTISK TIGER AS',
        location: {
            address: 'Glønavegen 2',
            postalCode: '6650',
            city: 'SURNADAL',
            municipal: 'SURNADAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '310661481',
        name: 'DIVERSE TANKEFULL TIGER AS',
        location: {
            address: 'Storgata 24',
            postalCode: '6413',
            city: 'MOLDE',
            municipal: 'MOLDE',
            country: 'Norge',
        },
    },
    {
        orgnr: '313843327',
        name: 'VÅRLIG BEVISST TIGER AS',
        location: {
            address: 'Eiksveien 31B',
            postalCode: '1359',
            city: 'EIKSMARKA',
            municipal: 'BÆRUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '310868590',
        name: 'BARMHJERTIG HÅNDFAST TIGER AS',
        location: {
            address: 'c/o Skravlete Granneoksesatellitt',
            postalCode: '5528',
            city: 'HAUGESUND',
            municipal: 'HAUGESUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '313231186',
        name: 'FRUKTBAR LEKKER TIGER AS',
        location: {
            address: 'Nymarksvegen 18',
            postalCode: '5652',
            city: 'ÅRLAND',
            municipal: 'SAMNANGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '310486531',
        name: 'PRODUKTIV VARSOM TIGER AS',
        location: {
            address: 'Rabbenveien 38',
            postalCode: '3039',
            city: 'DRAMMEN',
            municipal: 'DRAMMEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314241894',
        name: 'UMOTIVERT GEOMETRISK ISBJØRN SA',
        location: {
            address: 'Indre Toppen',
            postalCode: '6670',
            city: 'ØYDEGARD',
            municipal: 'TINGVOLL',
            country: 'Norge',
        },
    },
    {
        orgnr: '312190508',
        name: 'OPPSTEMT HENSYNSLØS TIGER AS',
        location: {
            address: 'Nordre Plassen',
            postalCode: '0765',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '313048896',
        name: 'RIKTIG FAST TIGER AS',
        location: {
            address: 'Årlivollvegen 3',
            postalCode: '7327',
            city: 'SVORKMO',
            municipal: 'ORKLAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '312537583',
        name: 'GREI POSITIV TIGER AS',
        location: {
            address: 'c/o Umake Boble',
            postalCode: '8007',
            city: 'BODØ',
            municipal: 'BODØ',
            country: 'Norge',
        },
    },
    {
        orgnr: '310547220',
        name: 'GJENSIDIG FRYKTSOM TIGER AS',
        location: {
            address: 'Kjelsåsveien 118C',
            postalCode: '0491',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '310150185',
        name: 'RISIKABEL OVERFØLSOM TIGER AS',
        location: {
            address: 'Mellomenga 63',
            postalCode: '3404',
            city: 'LIER',
            municipal: 'LIER',
            country: 'Norge',
        },
    },
    {
        orgnr: '310337161',
        name: 'VEIK FORSKJELLIG TIGER AS',
        location: {
            address: 'Ålefjærveien 163',
            postalCode: '4634',
            city: 'KRISTIANSAND S',
            municipal: 'KRISTIANSAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '310427594',
        name: 'PRATSOM UPRAKTISK TIGER AS',
        location: {
            address: 'Ytre Humpen',
            postalCode: '3737',
            city: 'SKIEN',
            municipal: 'SKIEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '313717062',
        name: 'UMAKE FILOSOFISK TIGER AS',
        location: {
            address: 'Høgsetgrenda 1B',
            postalCode: '7026',
            city: 'TRONDHEIM',
            municipal: 'TRONDHEIM',
            country: 'Norge',
        },
    },
    {
        orgnr: '313216284',
        name: 'STABIL FESTLIG TIGER AS',
        location: {
            address: 'Hamnegata 1C',
            postalCode: '8480',
            city: 'ANDENES',
            municipal: 'ANDØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '310048933',
        name: 'BLØT LIVLIG TIGER AS',
        location: {
            address: 'Idrettsvegen 103D',
            postalCode: '5353',
            city: 'STRAUME',
            municipal: 'ØYGARDEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314243684',
        name: 'SPETTETE KOMPLISERT TIGER AS',
        location: {
            address: 'Bjerklundveien 17',
            postalCode: '1807',
            city: 'ASKIM',
            municipal: 'INDRE ØSTFOLD',
            country: 'Norge',
        },
    },
    {
        orgnr: '310313513',
        name: 'FARLIG AUTONOM TIGER AS',
        location: {
            address: 'Økrivegen 35',
            postalCode: '2032',
            city: 'MAURA',
            municipal: 'NANNESTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '310192252',
        name: 'FIRKANTET FORNUFTIG TIGER AS',
        location: {
            address: 'Flekkenutsiktspunktet',
            postalCode: '9593',
            city: 'BREIVIKBOTN',
            municipal: 'HASVIK',
            country: 'Norge',
        },
    },
    {
        orgnr: '314102940',
        name: 'VÅRLIG PARAT TIGER AS',
        location: {
            address: 'Nedre Viddadalen',
            postalCode: '8190',
            city: 'SØRFJORDEN',
            municipal: 'RØDØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '313080293',
        name: 'SNILL ALMINNELIG TIGER AS',
        location: {
            address: 'Rjukanvegen 1066',
            postalCode: '3864',
            city: 'RAULAND',
            municipal: 'VINJE',
            country: 'Norge',
        },
    },
    {
        orgnr: '213509292',
        name: 'ULLEN USIKKER TIGER AS',
        location: {
            address: 'Semsbakken 19',
            postalCode: '3220',
            city: 'SANDEFJORD',
            municipal: 'SANDEFJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '213443712',
        name: 'FRISK VERDIFULL TIGER AS',
        location: {
            address: 'Geelmuydens gate 2A',
            postalCode: '3182',
            city: 'HORTEN',
            municipal: 'HORTEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '311063871',
        name: 'MORALSK SPISS TIGER AS',
        location: {
            address: 'Helgeplasset 137',
            postalCode: '5148',
            city: 'FYLLINGSDALEN',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314283546',
        name: 'ALLMEKTIG INKLUDERENDE TIGER AS',
        location: {
            address: 'Sentrumsveien 37A',
            postalCode: '3647',
            city: 'HVITTINGFOSS',
            municipal: 'KONGSBERG',
            country: 'Norge',
        },
    },
    {
        orgnr: '311063308',
        name: 'PRATSOM KOMPETENT TIGER AS',
        location: {
            address: 'Åkersgata 6',
            postalCode: '6600',
            city: 'SUNNDALSØRA',
            municipal: 'SUNNDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '310799963',
        name: 'NETT PARODISK TIGER AS',
        location: {
            address: 'Paradisgrende 122',
            postalCode: '3628',
            city: 'VEGGLI',
            municipal: 'ROLLAG',
            country: 'Norge',
        },
    },
    {
        orgnr: '313457397',
        name: 'EMOSJONELL FILOSOFISK TIGER AS',
        location: {
            address: 'Øverbyveien 251',
            postalCode: '3355',
            city: 'SOLUMSMOEN',
            municipal: 'SIGDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '313012131',
        name: 'PERFEKT AVANSERT INSEKT',
        location: {
            address: 'Vestre Elva',
            postalCode: '4529',
            city: 'BYREMO',
            municipal: 'LYNGDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '312166372',
        name: 'KOMPLETT TANKEFULL TIGER AS',
        location: {
            address: 'Buvikstranda 12',
            postalCode: '1622',
            city: 'GRESSVIK',
            municipal: 'FREDRIKSTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '313755290',
        name: 'MORSOM LIKEGYLDIG PUMA',
        location: {
            address: 'Mindeveien 29',
            postalCode: '7170',
            city: 'ÅFJORD',
            municipal: 'ÅFJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '314284275',
        name: 'FORDEKT ENTUSIASTISK TIGER AS',
        location: {
            address: 'Maridalsveien 128B',
            postalCode: '0461',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '313518841',
        name: 'UTHOLDEN FYLDIG TIGER AS',
        location: {
            address: 'Dikemarkveien 33',
            postalCode: '1385',
            city: 'ASKER',
            municipal: 'ASKER',
            country: 'Norge',
        },
    },
    {
        orgnr: '312903911',
        name: 'OPPFARENDE EMPATISK TIGER AS',
        location: {
            address: 'v/ Retorisk Spesialist',
            postalCode: '3222',
            city: 'SANDEFJORD',
            municipal: 'SANDEFJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '314283406',
        name: 'EGOISTISK MOSEGRODD TIGER AS',
        location: {
            address: 'Maleniusåsen 35',
            postalCode: '4230',
            city: 'SAND',
            municipal: 'SULDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '312221772',
        name: 'OMKOMMEN METT TIGER AS',
        location: {
            address: 'Stormyrvegen 21',
            postalCode: '2005',
            city: 'RÆLINGEN',
            municipal: 'RÆLINGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '313574512',
        name: 'RØD LYSTIG APE',
        location: {
            address: 'Mario Caprinos vei 2A',
            postalCode: '1367',
            city: 'SNARØYA',
            municipal: 'BÆRUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '213858122',
        name: 'SNILL MOSEGRODD TIGER AS',
        location: {
            address: 'Rynesåsen 41',
            postalCode: '8665',
            city: 'MOSJØEN',
            municipal: 'VEFSN',
            country: 'Norge',
        },
    },
    {
        orgnr: '310591033',
        name: 'REALISTISK LETT TIGER AS',
        location: {
            address: 'Strandvegen 188',
            postalCode: '2668',
            city: 'LESJASKOG',
            municipal: 'LESJA',
            country: 'Norge',
        },
    },
    {
        orgnr: '311088270',
        name: 'ORDKNAPP EMPATISK TIGER AS',
        location: {
            address: 'Rimstadbukta 20',
            postalCode: '6630',
            city: 'TINGVOLL',
            municipal: 'TINGVOLL',
            country: 'Norge',
        },
    },
    {
        orgnr: '311702025',
        name: 'KLASSISK GRUNN TIGER AS',
        location: {
            address: 'Uskedalsvegen 588',
            postalCode: '5463',
            city: 'USKEDALEN',
            municipal: 'KVINNHERAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '312215152',
        name: 'KRITISK AKSELERERENDE TIGER AS',
        location: {
            address: 'Mosserødveien 31',
            postalCode: '3226',
            city: 'SANDEFJORD',
            municipal: 'SANDEFJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '312906708',
        name: 'TRÅDLØS POMPØS TIGER AS',
        location: {
            address: 'Holdalsnuten 5',
            postalCode: '4633',
            city: 'KRISTIANSAND S',
            municipal: 'KRISTIANSAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '310328804',
        name: 'FORMBAR STANDHAFTIG TIGER AS',
        location: {
            address: 'Holmenomveien',
            postalCode: '9580',
            city: 'BERGSFJORD',
            municipal: 'LOPPA',
            country: 'Norge',
        },
    },
    {
        orgnr: '313677168',
        name: 'FRUKTBAR URETTFERDIG TIGER AS',
        location: {
            address: 'Indre Utmarka',
            postalCode: '1284',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '310352101',
        name: 'SOFISTIKERT MOBIL TIGER AS',
        location: {
            address: 'Ileveien 12',
            postalCode: '4310',
            city: 'HOMMERSÅK',
            municipal: 'SANDNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '313704602',
        name: 'INTEGRERT LYSTIG TIGER AS',
        location: {
            address: 'Kippersundvegen 12',
            postalCode: '6430',
            city: 'BUD',
            municipal: 'HUSTADVIKA',
            country: 'Norge',
        },
    },
    {
        orgnr: '311738224',
        name: 'LEI GOD TIGER AS',
        location: {
            address: 'Nedre Gleinåsen 19',
            postalCode: '3440',
            city: 'RØYKEN',
            municipal: 'ASKER',
            country: 'Norge',
        },
    },
    {
        orgnr: '310325562',
        name: 'EKTE BEMERKELSESVERDIG TIGER AS',
        location: {
            address: 'Rossmollgata 41',
            postalCode: '9601',
            city: 'HAMMERFEST',
            municipal: 'HAMMERFEST',
            country: 'Norge',
        },
    },
    {
        orgnr: '312954400',
        name: 'ROLIG OBSERVANT TIGER AS',
        location: {
            address: 'c/o Samtidigsjenert Tapper Bursdag',
            postalCode: '8976',
            city: 'VEVELSTAD',
            municipal: 'VEVELSTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '212805122',
        name: 'FORSTANDIG HUSLØS TIGER AS',
        location: {
            address: 'Brannstasjonsveien 24',
            postalCode: '4312',
            city: 'SANDNES',
            municipal: 'SANDNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '212650412',
        name: 'LOGISK ANALYSERENDE TIGER AS',
        location: {
            address: 'Vikane 1',
            postalCode: '6995',
            city: 'KYRKJEBØ',
            municipal: 'HØYANGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '313833550',
        name: 'VÅRLIG GRÅ TIGER AS',
        location: {
            address: 'Richard Nordraaks gate 1',
            postalCode: '5018',
            city: 'BERGEN',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '312672146',
        name: 'ALLMEKTIG STRIDLYNT TIGER AS',
        location: {
            address: 'v/ Godmomentan Kalv',
            postalCode: '6812',
            city: 'FØRDE',
            municipal: 'SUNNFJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '211764082',
        name: 'KONKURRANSEDYKTIG RØD TIGER AS',
        location: {
            address: 'Vollgata 16C',
            postalCode: '2213',
            city: 'KONGSVINGER',
            municipal: 'KONGSVINGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '314198999',
        name: 'BETYDELIG GJENSIDIG TIGER AS',
        location: {
            address: 'Feiosvegen 471',
            postalCode: '6895',
            city: 'FEIOS',
            municipal: 'VIK',
            country: 'Norge',
        },
    },
    {
        orgnr: '310340049',
        name: 'SMART SALIG TIGER AS',
        location: {
            address: 'Strandveien 4B',
            postalCode: '3186',
            city: 'HORTEN',
            municipal: 'HORTEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '310495638',
        name: 'GUL ORDKNAPP TIGER AS',
        location: {
            address: 'Kilbuvegen 12',
            postalCode: '4820',
            city: 'FROLAND',
            municipal: 'FROLAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '312737264',
        name: 'KLAM FANTASILØS TIGER AS',
        location: {
            address: 'Båthavnveien 6',
            postalCode: '1655',
            city: 'SELLEBAKK',
            municipal: 'FREDRIKSTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '314241215',
        name: 'KLARTENKT SLAPP TIGER AS',
        location: {
            address: 'Stasjonsveien 1',
            postalCode: '0776',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '310715417',
        name: 'NY RØD TIGER AS',
        location: {
            address: 'Veverbakken 91',
            postalCode: '1536',
            city: 'MOSS',
            municipal: 'MOSS',
            country: 'Norge',
        },
    },
    {
        orgnr: '310029971',
        name: 'BEGEISTRET KALD TIGER AS',
        location: {
            address: 'Kråkåsveien 58',
            postalCode: '3229',
            city: 'SANDEFJORD',
            municipal: 'SANDEFJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '314255003',
        name: 'UMOTIVERT SLITEN TIGER AS',
        location: {
            address: 'Steinneset 12',
            postalCode: '5200',
            city: 'OS',
            municipal: 'BJØRNAFJORDEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '311138472',
        name: 'TAKTFULL IDIOTSIKKER TIGER AS',
        location: {
            address: 'Via Nova 2',
            postalCode: '1162',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '313493385',
        name: 'HORISONTAL MATEMATISK TIGER AS',
        location: {
            address: 'Øvre Utkanten',
            postalCode: '5038',
            city: 'BERGEN',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '212830372',
        name: 'DYREBAR OVERNATURLIG TIGER AS',
        location: {
            address: 'Havnevikvegen 33',
            postalCode: '6013',
            city: 'ÅLESUND',
            municipal: 'ÅLESUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '314099931',
        name: 'PERFEKT RU TIGER AS',
        location: {
            address: '',
            postalCode: '7224',
            city: 'MELHUS',
            municipal: 'MELHUS',
            country: 'Norge',
        },
    },
    {
        orgnr: '314176677',
        name: 'MOBIL VENNLIG TIGER AS',
        location: {
            address: 'Kastanjeveien 18',
            postalCode: '4824',
            city: 'BJORBEKK',
            municipal: 'ARENDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '312842963',
        name: 'HÅNDFAST SMISKENDE TIGER AS',
        location: {
            address: 'Nedre Ulsetskogen 72',
            postalCode: '5119',
            city: 'ULSET',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '310030945',
        name: 'UPRAKTISK NATURSTRIDIG TIGER AS',
        location: {
            address: '',
            postalCode: '2646',
            city: 'GÅLÅ',
            municipal: 'SØR-FRON',
            country: 'Norge',
        },
    },
    {
        orgnr: '310469416',
        name: 'HÅNDLAGET TØRR TIGER AS',
        location: {
            address: 'Dåfjordvegen 109',
            postalCode: '5410',
            city: 'SAGVÅG',
            municipal: 'STORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '313919501',
        name: 'ØKOLOGISK FLAT TIGER AS',
        location: {
            address: 'Seljeveien 16',
            postalCode: '4622',
            city: 'KRISTIANSAND S',
            municipal: 'KRISTIANSAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '313029638',
        name: 'KJÆRLIG REFLEKTERENDE TIGER AS',
        location: {
            address: 'Sauesundet 68',
            postalCode: '6985',
            city: 'ATLØY',
            municipal: 'ASKVOLL',
            country: 'Norge',
        },
    },
    {
        orgnr: '314248694',
        name: 'UPRESIS JOVIAL TIGER AS',
        location: {
            address: 'c/o Rakrygget Skjønn Brande',
            postalCode: '3413',
            city: 'LIER',
            municipal: 'LIER',
            country: 'Norge',
        },
    },
    {
        orgnr: '312469766',
        name: 'POMPØS ORDENTLIG TIGER AS',
        location: {
            address: 'Åkvikveien 12',
            postalCode: '8892',
            city: 'SUNDØY',
            municipal: 'LEIRFJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '313910687',
        name: 'ROSA REFLEKTERENDE TIGER AS',
        location: {
            address: '',
            postalCode: '8063',
            city: 'VÆRØY',
            municipal: 'VÆRØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '314201310',
        name: 'LUN SOSIAL TIGER AS',
        location: {
            address: 'Osloveien 38N',
            postalCode: '1440',
            city: 'DRØBAK',
            municipal: 'FROGN',
            country: 'Norge',
        },
    },
    {
        orgnr: '311750895',
        name: 'MUSIKALSK GLAD TIGER AS',
        location: {
            address: 'Eikelandsveien 104',
            postalCode: '4595',
            city: 'TINGVATN',
            municipal: 'HÆGEBOSTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '313468100',
        name: 'VARM SKRIVEFØR TIGER AS',
        location: {
            address: 'c/o Blaut Reservert Trommis',
            postalCode: '1423',
            city: 'SKI',
            municipal: 'NORDRE FOLLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '313436233',
        name: 'PRIKKETE KOMFORTABEL BILLE IKS',
        location: {
            address: 'Øvre Kleiven',
            postalCode: '3022',
            city: 'DRAMMEN',
            municipal: 'DRAMMEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '313150542',
        name: 'BESTEMT NYSGJERRIG TIGER AS',
        location: {
            address: 'Indre Fjordbotnet',
            postalCode: '1866',
            city: 'BÅSTAD',
            municipal: 'INDRE ØSTFOLD',
            country: 'Norge',
        },
    },
    {
        orgnr: '312528886',
        name: 'BETYDELIG NORMAL TIGER AS',
        location: {
            address: 'v/ Freidig Lysegrønn Fruktbutikk',
            postalCode: '5232',
            city: 'PARADIS',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314289455',
        name: 'ANSVARSFULL HÅRSÅR TIGER AS',
        location: {
            address: 'Haugvegen 21',
            postalCode: '6015',
            city: 'ÅLESUND',
            municipal: 'ÅLESUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '310319716',
        name: 'UTGÅTT USNOBBET TIGER AS',
        location: {
            address: 'Eikveien 85',
            postalCode: '3060',
            city: 'SVELVIK',
            municipal: 'DRAMMEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '312769840',
        name: 'VIKTIG FLEKSIBEL TIGER AS',
        location: {
            address: 'Kindsåsfaret 19',
            postalCode: '3533',
            city: 'TYRISTRAND',
            municipal: 'RINGERIKE',
            country: 'Norge',
        },
    },
    {
        orgnr: '313270661',
        name: 'GNIEN UNDERLIG TIGER AS',
        location: {
            address: 'v/ Komplett Suppetevling',
            postalCode: '0178',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '310259624',
        name: 'KRITISK ANSTENDIG TIGER AS',
        location: {
            address: 'Garlivegen 35',
            postalCode: '2900',
            city: 'FAGERNES',
            municipal: 'NORD-AURDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '310084778',
        name: 'RISIKABEL KUL TIGER AS',
        location: {
            address: 'Gimleveien 70',
            postalCode: '1786',
            city: 'HALDEN',
            municipal: 'HALDEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '312609274',
        name: 'AKTPÅGIVENDE FILOSOFISK TIGER AS',
        location: {
            address: 'Selåsvatn 184',
            postalCode: '4868',
            city: 'SELÅSVATN',
            municipal: 'ÅMLI',
            country: 'Norge',
        },
    },
    {
        orgnr: '312709643',
        name: 'MORSK LYDIG TIGER AS',
        location: {
            address: 'Kløvfaret 19',
            postalCode: '3280',
            city: 'TJODALYNG',
            municipal: 'LARVIK',
            country: 'Norge',
        },
    },
    {
        orgnr: '312525097',
        name: 'KONKRET SUBJEKTIV TIGER AS',
        location: {
            address: 'Robølsvegen 333',
            postalCode: '2940',
            city: 'HEGGENES',
            municipal: 'ØYSTRE SLIDRE',
            country: 'Norge',
        },
    },
    {
        orgnr: '312616416',
        name: 'FJONG UNGT ISBJØRN SA',
        location: {
            address: '',
            postalCode: '3560',
            city: 'HEMSEDAL',
            municipal: 'HEMSEDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '313836304',
        name: 'SLAKK FORNEM PIGGSVIN',
        location: {
            address: 'Fagerhøyveien 6',
            postalCode: '1369',
            city: 'STABEKK',
            municipal: 'BÆRUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '313486621',
        name: 'UTNYTTENDE SLAKK MUS',
        location: {
            address: 'Linjeveien 2',
            postalCode: '1920',
            city: 'SØRUMSAND',
            municipal: 'LILLESTRØM',
            country: 'Norge',
        },
    },
    {
        orgnr: '310252433',
        name: 'PERFEKT GLUPSK TIGER AS',
        location: {
            address: 'Langnesvegen 20',
            postalCode: '9016',
            city: 'TROMSØ',
            municipal: 'TROMSØ',
            country: 'Norge',
        },
    },
    {
        orgnr: '310599867',
        name: 'VAKKER SALT TIGER AS',
        location: {
            address: 'Hangerslettvegen 597',
            postalCode: '7070',
            city: 'BOSBERG',
            municipal: 'TRONDHEIM',
            country: 'Norge',
        },
    },
    {
        orgnr: '310366722',
        name: 'UNGT DIREKTE TIGER AS',
        location: {
            address: 'c/o Impulsiv Tomt',
            postalCode: '2436',
            city: 'VÅLER I SOLØR',
            municipal: 'ÅSNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '313902056',
        name: 'PÅPASSELIG PROAKTIV TIGER AS',
        location: {
            address: 'Kalbakkveien 11B',
            postalCode: '0953',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '313076202',
        name: 'PATENT FRYKTLØS TIGER AS',
        location: {
            address: 'Lifjellvegen 74',
            postalCode: '3804',
            city: 'BØ I TELEMARK',
            municipal: 'MIDT-TELEMARK',
            country: 'Norge',
        },
    },
    {
        orgnr: '313998223',
        name: 'STOR ROSA TIGER AS',
        location: {
            address: 'v/ Treg*gutt Delepris',
            postalCode: '4013',
            city: 'STAVANGER',
            municipal: 'STAVANGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '310290637',
        name: 'UGJENNOMSIKTIG HISTORISK TIGER AS',
        location: {
            address: 'Kvisselvegen 195',
            postalCode: '2364',
            city: 'NÆROSET',
            municipal: 'RINGSAKER',
            country: 'Norge',
        },
    },
    {
        orgnr: '313756920',
        name: 'DIVERSE SKYFRI TIGER AS',
        location: {
            address: 'Møllefaret 34F',
            postalCode: '0750',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '310957976',
        name: 'DOBBEL ENGASJERT STRUTS AS',
        location: {
            address: '',
            postalCode: '',
            city: undefined,
            municipal: undefined,
            country: undefined,
        },
    },
    {
        orgnr: '313933245',
        name: 'OPERATIV UTHOLDEN TIGER AS',
        location: {
            address: 'Dølebakken 6',
            postalCode: '3215',
            city: 'SANDEFJORD',
            municipal: 'SANDEFJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '314100735',
        name: 'LYDIG ANSTENDIG TIGER AS',
        location: {
            address: 'Treungvegen 81D',
            postalCode: '3880',
            city: 'DALEN',
            municipal: 'TOKKE',
            country: 'Norge',
        },
    },
    {
        orgnr: '213236202',
        name: 'REDELIG VIKTIG TIGER AS',
        location: {
            address: 'Røneidsgrandane 5',
            postalCode: '6868',
            city: 'GAUPNE',
            municipal: 'LUSTER',
            country: 'Norge',
        },
    },
    {
        orgnr: '314258347',
        name: 'AKTIV LEDENDE TIGER AS',
        location: {
            address: 'v/ Óppgitt Bagatellbris',
            postalCode: '0951',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '313788423',
        name: 'SMAL VENNLIG TIGER AS',
        location: {
            address: 'Landstedetosen',
            postalCode: '4910',
            city: 'LYNGØR',
            municipal: 'TVEDESTRAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '313443272',
        name: 'OVERFLADISK MELANKOLSK TIGER AS',
        location: {
            address: 'Østenåsveien 23',
            postalCode: '1344',
            city: 'HASLUM',
            municipal: 'BÆRUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '310690376',
        name: 'TILGIVENDE ESTETISK TIGER AS',
        location: {
            address: 'Halvdan Lunds veg 3',
            postalCode: '2413',
            city: 'ELVERUM',
            municipal: 'ELVERUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '313568385',
        name: 'ALTETENDE FYSISK TIGER AS',
        location: {
            address: 'Johan Bojers vei 282',
            postalCode: '7100',
            city: 'RISSA',
            municipal: 'INDRE FOSEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '214244802',
        name: 'MATT OPPJAGET TIGER AS',
        location: {
            address: 'Thorvald Meyers gate 83C',
            postalCode: '0552',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '313763846',
        name: 'OPPBLÅST FJONG TIGER AS',
        location: {
            address: 'Hans Strømsvei 15',
            postalCode: '3055',
            city: 'KROKSTADELVA',
            municipal: 'DRAMMEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '211006072',
        name: 'AUTONOM GREI TIGER AS',
        location: {
            address: 'Søndre Fjellheimen',
            postalCode: '5093',
            city: 'BERGEN',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '313113701',
        name: 'SIGEN RAFFINERT TIGER AS',
        location: {
            address: 'Rubinvegen 12',
            postalCode: '4355',
            city: 'KVERNALAND',
            municipal: 'TIME',
            country: 'Norge',
        },
    },
    {
        orgnr: '313405702',
        name: 'SKRAVLETE GLAD TIGER AS',
        location: {
            address: 'Sondre Nordheims vei 13',
            postalCode: '3610',
            city: 'KONGSBERG',
            municipal: 'KONGSBERG',
            country: 'Norge',
        },
    },
    {
        orgnr: '312810255',
        name: 'UTHOLDEN UFORGJENGELIG TIGER AS',
        location: {
            address: 'Skogveien 21',
            postalCode: '1467',
            city: 'STRØMMEN',
            municipal: 'LILLESTRØM',
            country: 'Norge',
        },
    },
    {
        orgnr: '312447762',
        name: 'UFØLSOM USANNFERDIG KROKODILLE',
        location: {
            address: 'Lokes vei 5',
            postalCode: '1782',
            city: 'HALDEN',
            municipal: 'HALDEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '310458635',
        name: 'USELVSTENDIG OVERFØLSOM TIGER AS',
        location: {
            address: 'Kurveien 7',
            postalCode: '0495',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '310663808',
        name: 'TILLITSFULL URETTFERDIG TIGER AS',
        location: {
            address: 'Hørtevegen 273',
            postalCode: '3810',
            city: 'GVARV',
            municipal: 'MIDT-TELEMARK',
            country: 'Norge',
        },
    },
    {
        orgnr: '312676095',
        name: 'NYTTIG AUTORISERT TIGER AS',
        location: {
            address: 'Bjarne Hansens vei 15',
            postalCode: '3680',
            city: 'NOTODDEN',
            municipal: 'NOTODDEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '310091502',
        name: 'SAMLET HÅNDLAGET APE',
        location: {
            address: 'v/ Dyp Babybag',
            postalCode: '1433',
            city: 'ÅS',
            municipal: 'ÅS',
            country: 'Norge',
        },
    },
    {
        orgnr: '312986698',
        name: 'UFUNKSJONELL KJEMPENDE MUS',
        location: {
            address: 'Gierløffs vei 20',
            postalCode: '3770',
            city: 'KRAGERØ',
            municipal: 'KRAGERØ',
            country: 'Norge',
        },
    },
    {
        orgnr: '314008448',
        name: 'AUTORISERT RASTLØS TIGER AS',
        location: {
            address: 'Signalveien 20',
            postalCode: '1597',
            city: 'MOSS',
            municipal: 'MOSS',
            country: 'Norge',
        },
    },
    {
        orgnr: '310815586',
        name: 'UPRAKTISK UNDERDANIG TIGER AS',
        location: {
            address: 'Hellesvingen 58',
            postalCode: '1336',
            city: 'SANDVIKA',
            municipal: 'BÆRUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '210314482',
        name: 'UFØLSOM HEVNGJERRIG TIGER AS',
        location: {
            address: 'Bekken',
            postalCode: '4311',
            city: 'HOMMERSÅK',
            municipal: 'SANDNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '313317110',
        name: 'DEILIG KONSEKVENT TIGER AS',
        location: {
            address: 'Gylsvegen 10',
            postalCode: '6220',
            city: 'STRAUMGJERDE',
            municipal: 'SYKKYLVEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '312511312',
        name: 'SMAL SJENERT TIGER AS',
        location: {
            address: 'Rustadvegen 8',
            postalCode: '2834',
            city: 'RAUFOSS',
            municipal: 'VESTRE TOTEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '313107981',
        name: 'GJENSIDIG NATURLIG TIGER AS',
        location: {
            address: 'Ytre Feltet',
            postalCode: '4173',
            city: 'NORD-HIDLE',
            municipal: 'STAVANGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '312808838',
        name: 'IVRIG ENGASJERT TIGER AS',
        location: {
            address: 'Uelands gate 57D',
            postalCode: '0457',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '310409227',
        name: 'UTÅLMODIG FYLDIG TIGER AS',
        location: {
            address: 'Lyngholmvegen 22',
            postalCode: '5550',
            city: 'SVEIO',
            municipal: 'SVEIO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314079035',
        name: 'EMPIRISK UFORNUFTIG TIGER AS',
        location: {
            address: '',
            postalCode: '2120',
            city: 'SAGSTUA',
            municipal: 'NORD-ODAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '313785262',
        name: 'POMPØS MISFORNØYD TIGER AS',
        location: {
            address: 'Skjerpeveien 1',
            postalCode: '4376',
            city: 'HELLELAND',
            municipal: 'EIGERSUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '310542660',
        name: 'RETORISK TALEFØR TIGER AS',
        location: {
            address: 'Førrisdalveien 304',
            postalCode: '1894',
            city: 'RAKKESTAD',
            municipal: 'RAKKESTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '212738662',
        name: 'JUSTERBAR INTELLIGENT HUND DA',
        location: {
            address: 'Iledalsveien 24',
            postalCode: '3410',
            city: 'SYLLING',
            municipal: 'LIER',
            country: 'Norge',
        },
    },
    {
        orgnr: '310429937',
        name: 'FREDFULL HORISONTAL TIGER AS',
        location: {
            address: 'Hestehagen 5',
            postalCode: '9321',
            city: 'MOEN',
            municipal: 'MÅLSELV',
            country: 'Norge',
        },
    },
    {
        orgnr: '310839221',
        name: 'EPISK KURSIV TIGER AS',
        location: {
            address: 'Ekornrudvegen 18',
            postalCode: '2052',
            city: 'JESSHEIM',
            municipal: 'ULLENSAKER',
            country: 'Norge',
        },
    },
    {
        orgnr: '314250591',
        name: 'FORSIKTIG KALD TIGER AS',
        location: {
            address: 'Verftsbassenget 12',
            postalCode: '3188',
            city: 'HORTEN',
            municipal: 'HORTEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '312174189',
        name: 'SKAMFULL UNDERFUNDIG TIGER AS',
        location: {
            address: 'Aspåsvegen 1',
            postalCode: '8661',
            city: 'MOSJØEN',
            municipal: 'VEFSN',
            country: 'Norge',
        },
    },
    {
        orgnr: '312602814',
        name: 'USJENERT POSSESSIV MUS',
        location: {
            address: 'Ørehaug 18',
            postalCode: '5414',
            city: 'STORD',
            municipal: 'STORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '314248996',
        name: 'HÅNDLAGET MEDGJØRLIG ISBJØRN SA',
        location: {
            address: 'Skogkanten 34',
            postalCode: '1410',
            city: 'KOLBOTN',
            municipal: 'NORDRE FOLLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '310177768',
        name: 'MINIMALISTISK ØKOLOGISK KATT GRAVEMASKIN',
        location: {
            address: '',
            postalCode: '7690',
            city: 'MOSVIK',
            municipal: 'INDERØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '211195312',
        name: 'TREG TILBAKEHOLDEN TIGER AS',
        location: {
            address: '',
            postalCode: '6140',
            city: 'SYVDE',
            municipal: 'VANYLVEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '312405180',
        name: 'SIST USTABIL TIGER AS',
        location: {
            address: 'Øvre Torvgate 40',
            postalCode: '2821',
            city: 'GJØVIK',
            municipal: 'GJØVIK',
            country: 'Norge',
        },
    },
    {
        orgnr: '310995045',
        name: 'PÅLITELIG AKSELERERENDE TIGER AS',
        location: {
            address: '',
            postalCode: '6453',
            city: 'KLEIVE',
            municipal: 'MOLDE',
            country: 'Norge',
        },
    },
    {
        orgnr: '312274841',
        name: 'RETTFERDIG ØVRIG TIGER AS',
        location: {
            address: 'Nordre Stranden',
            postalCode: '1164',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '312802090',
        name: 'UNG DYP TIGER AS',
        location: {
            address: 'Arbeidergata 19',
            postalCode: '3050',
            city: 'MJØNDALEN',
            municipal: 'DRAMMEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '311785192',
        name: 'GRATIS STRAFFET TIGER AS',
        location: {
            address: 'Vidjeveien 23',
            postalCode: '9603',
            city: 'HAMMERFEST',
            municipal: 'HAMMERFEST',
            country: 'Norge',
        },
    },
    {
        orgnr: '313275485',
        name: 'NETT NØDVENDIG TIGER AS',
        location: {
            address: 'Slorhøgda 20',
            postalCode: '1407',
            city: 'VINTERBRO',
            municipal: 'ÅS',
            country: 'Norge',
        },
    },
    {
        orgnr: '310404179',
        name: 'MORSK HÅNDFAST TIGER AS',
        location: {
            address: 'Rovdestranda 999',
            postalCode: '6141',
            city: 'ROVDE',
            municipal: 'VANYLVEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '310427357',
        name: 'AKUSTISK ULIK TIGER AS',
        location: {
            address: 'v/ Artig Allsidig Savanne',
            postalCode: '5019',
            city: 'BERGEN',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '310764272',
        name: 'UMOTIVERT JUSTERBAR APE',
        location: {
            address: 'c/o Realkjøpmann',
            postalCode: '3184',
            city: 'BORRE',
            municipal: 'HORTEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '310631469',
        name: 'SPRUDLENDE MATT TIGER AS',
        location: {
            address: 'Ryfylkeveien 595',
            postalCode: '4308',
            city: 'SANDNES',
            municipal: 'SANDNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '310673617',
        name: 'TENTATIV RESERVERT TIGER AS',
        location: {
            address: 'Søndre Avstikkeren',
            postalCode: '4985',
            city: 'VEGÅRSHEI',
            municipal: 'VEGÅRSHEI',
            country: 'Norge',
        },
    },
    {
        orgnr: '313188957',
        name: 'PRATSOM ENTUSIASTISK TIGER AS',
        location: {
            address: 'Prestrudvegen 85',
            postalCode: '2625',
            city: 'FÅBERG',
            municipal: 'LILLEHAMMER',
            country: 'Norge',
        },
    },
    {
        orgnr: '310118028',
        name: 'VERTIKAL EKTE TIGER AS',
        location: {
            address: 'Hognesaunvegen 101A',
            postalCode: '7513',
            city: 'STJØRDAL',
            municipal: 'STJØRDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '313871479',
        name: 'PLUTSELIG OVERBEVISENDE PIGGSVIN',
        location: {
            address: 'Brusegårdsvegen 17B',
            postalCode: '5306',
            city: 'ERDAL',
            municipal: 'ASKØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '312426080',
        name: 'FYSISK JUSTERBAR TIGER AS',
        location: {
            address: 'Bråmyra 30A',
            postalCode: '7074',
            city: 'SPONGDAL',
            municipal: 'TRONDHEIM',
            country: 'Norge',
        },
    },
    {
        orgnr: '313673413',
        name: 'HENSYNSFULL OPPSTEMT TIGER AS',
        location: {
            address: 'Nedre Heia',
            postalCode: '5285',
            city: 'BRUVIK',
            municipal: 'OSTERØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '310562041',
        name: 'VÅRLIG FLINK TIGER AS',
        location: {
            address: 'Solemsvegen 49',
            postalCode: '7863',
            city: 'OVERHALLA',
            municipal: 'OVERHALLA',
            country: 'Norge',
        },
    },
    {
        orgnr: '314282574',
        name: 'FREIDIG OPPLAGT TIGER AS',
        location: {
            address: 'Nordre Kongsveg 605',
            postalCode: '2372',
            city: 'BRØTTUM',
            municipal: 'RINGSAKER',
            country: 'Norge',
        },
    },
    {
        orgnr: '312416336',
        name: 'OVERBEVISENDE OPPLAGT TIGER AS',
        location: {
            address: 'Kirkegata 19A',
            postalCode: '4307',
            city: 'SANDNES',
            municipal: 'SANDNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '314279913',
        name: 'DEMOKRATISK LILLA TIGER AS',
        location: {
            address: 'Lidfeltet 15',
            postalCode: '6393',
            city: 'TOMREFJORD',
            municipal: 'VESTNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '310582778',
        name: 'OPPBLÅST MOTIVERT TIGER AS',
        location: {
            address: 'Gardstøl 25',
            postalCode: '5518',
            city: 'HAUGESUND',
            municipal: 'HAUGESUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '312819856',
        name: 'ALLMEKTIG OMKOMMEN TIGER AS',
        location: {
            address: 'Kirkeveien 47A',
            postalCode: '1363',
            city: 'HØVIK',
            municipal: 'BÆRUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '310570354',
        name: 'UTMERKET KNUSLETE APE',
        location: {
            address: 'Sitjevegen 11',
            postalCode: '3870',
            city: 'FYRESDAL',
            municipal: 'FYRESDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '312476649',
        name: 'SUBTIL KONKURRANSEDYKTIG TIGER AS',
        location: {
            address: 'Bydalen allé 22',
            postalCode: '1604',
            city: 'FREDRIKSTAD',
            municipal: 'FREDRIKSTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '310945099',
        name: 'UAVHENGIG DYNAMISK TIGER AS',
        location: {
            address: 'Johan Bojers vei 36',
            postalCode: '7100',
            city: 'RISSA',
            municipal: 'INDRE FOSEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '311178016',
        name: 'FREIDIG USELVISK TIGER AS',
        location: {
            address: 'Lunheimvegen 24',
            postalCode: '7540',
            city: 'KLÆBU',
            municipal: 'TRONDHEIM',
            country: 'Norge',
        },
    },
    {
        orgnr: '312788454',
        name: 'LYSELILLA SUBJEKTIV TIGER AS',
        location: {
            address: 'Storevegen 16',
            postalCode: '6884',
            city: 'ØVRE ÅRDAL',
            municipal: 'ÅRDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '310063339',
        name: 'HÅNDLAGET FJONG TIGER AS',
        location: {
            address: 'Københavngata 14B',
            postalCode: '0566',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '313316130',
        name: 'FREIDIG STOR ISBJØRN SA',
        location: {
            address: 'Vollsveien 166',
            postalCode: '1359',
            city: 'EIKSMARKA',
            municipal: 'BÆRUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '313749681',
        name: 'ARITMETISK MORSOM TIGER AS',
        location: {
            address: 'Hammers gate 14',
            postalCode: '4371',
            city: 'EGERSUND',
            municipal: 'EIGERSUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '314243005',
        name: 'SLEM TANKEFULL TIGER AS',
        location: {
            address: 'Symreveien 1B',
            postalCode: '1182',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '213512552',
        name: 'KOMPATIBEL VÅRLIG ISBJØRN SA',
        location: {
            address: "Paulus' plass 3C",
            postalCode: '0554',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '313093875',
        name: 'UNDERFUNDIG UFORGJENGELIG TIGER AS',
        location: {
            address: 'Kronprinsens gate 3',
            postalCode: '9900',
            city: 'KIRKENES',
            municipal: 'SØR-VARANGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '310705039',
        name: 'HELLIG ØVRIG TIGER AS',
        location: {
            address: 'Nordre Jordet',
            postalCode: '0474',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '313267377',
        name: 'OPPRETT SENSITIV TIGER AS',
        location: {
            address: 'Askvegen 804',
            postalCode: '5307',
            city: 'ASK',
            municipal: 'ASKØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '210004742',
        name: 'UNDERDANIG OVEREKSPONERT TIGER AS',
        location: {
            address: 'Terminalgata 66',
            postalCode: '9019',
            city: 'TROMSØ',
            municipal: 'TROMSØ',
            country: 'Norge',
        },
    },
    {
        orgnr: '314260023',
        name: 'LETT USELVSTENDIG TIGER AS',
        location: {
            address: 'Østerøyveien 38',
            postalCode: '3236',
            city: 'SANDEFJORD',
            municipal: 'SANDEFJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '313024474',
        name: 'LIVSGLAD USNOBBET TIGER AS',
        location: {
            address: 'Stiksmoveien 14',
            postalCode: '1892',
            city: 'DEGERNES',
            municipal: 'RAKKESTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '313912221',
        name: 'USENSUELL IVRIG TIGER AS',
        location: {
            address: 'Hakavikveien 888',
            postalCode: '3322',
            city: 'FISKUM',
            municipal: 'ØVRE EIKER',
            country: 'Norge',
        },
    },
    {
        orgnr: '313941388',
        name: 'HANDLEKRAFTIG NØDVENDIG TIGER AS',
        location: {
            address: 'Furulyvegen 1',
            postalCode: '5416',
            city: 'STORD',
            municipal: 'STORD',
            country: 'Norge',
        },
    },
];

export default devVirksomheter;
