import { Arbeidsgiverforslag } from '../opprett-ny-stilling/VelgArbeidsgiver';

const devVirksomheter: Arbeidsgiverforslag[] = [
    {
        orgnr: '311936255',
        name: 'MINKENDE VENSTRE TIGER AS',
        location: {
            address: 'Parkveien 1',
            postalCode: '4790',
            city: 'LILLESAND',
            municipal: 'LILLESAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '314472764',
        name: 'UFØLSOM MOSEGRODD TIGER AS',
        location: {
            address: 'Nesvegen 82',
            postalCode: '6010',
            city: 'ÅLESUND',
            municipal: 'ÅLESUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '315883415',
        name: 'ROBUST EMOSJONELL KATT DREGG',
        location: {
            address: 'Gulsvikvegen 229',
            postalCode: '3539',
            city: 'FLÅ',
            municipal: 'FLÅ',
            country: 'Norge',
        },
    },
    {
        orgnr: '311202448',
        name: 'KJÆR FLINK TIGER AS',
        location: {
            address: 'Åsheimveien 42',
            postalCode: '3490',
            city: 'KLOKKARSTUA',
            municipal: 'ASKER',
            country: 'Norge',
        },
    },
    {
        orgnr: '315802369',
        name: 'SOFISTIKERT FORNEM TIGER AS',
        location: {
            address: 'Syrenveien 5',
            postalCode: '1777',
            city: 'HALDEN',
            municipal: 'HALDEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314906403',
        name: 'KUL SUBTIL FJELLREV',
        location: {
            address: 'Bjørnheimveien 2E',
            postalCode: '1086',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '315908558',
        name: 'URIMELIG ALTETENDE TIGER AS',
        location: {
            address: 'Ekebergveien 65',
            postalCode: '1181',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '311632701',
        name: 'SUBTIL KOMPLETT TIGER AS',
        location: {
            address: '',
            postalCode: '8489',
            city: 'NORDMELA',
            municipal: 'ANDØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '315117941',
        name: 'GØYAL KLAM FJELLREV',
        location: {
            address: 'Øvre Båtstøendyngen',
            postalCode: '5387',
            city: 'MØKSTER',
            municipal: 'AUSTEVOLL',
            country: 'Norge',
        },
    },
    {
        orgnr: '314993934',
        name: 'OVERSIKTLIG HEMMELIGHETSFULL TIGER AS',
        location: {
            address: 'Åkebergveien 23',
            postalCode: '0650',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314600258',
        name: 'KUNNSKAPSRIK TILBAKEHOLDEN FJELLREV',
        location: {
            address: '',
            postalCode: '7298',
            city: 'BUDALEN',
            municipal: 'MIDTRE GAULDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '314538269',
        name: 'ELASTISK UTGÅTT FJELLREV',
        location: {
            address: 'Sandakerveien 133',
            postalCode: '0484',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '311569384',
        name: 'KONKRET INNBRINGENDE TIGER AS',
        location: {
            address: 'Ospabakken 1A',
            postalCode: '4306',
            city: 'SANDNES',
            municipal: 'SANDNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '315723213',
        name: 'ESTETISK BLAUT TIGER AS',
        location: {
            address: 'c/o From Seilbåt',
            postalCode: '6470',
            city: 'ERESFJORD',
            municipal: 'MOLDE',
            country: 'Norge',
        },
    },
    {
        orgnr: '311242415',
        name: 'EIERSEKSJONSSAMEIET USENSUELL LYSEBLÅ LØVE',
        location: {
            address: 'Tyslevveien 44A',
            postalCode: '1163',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314599098',
        name: 'SKAMFULL ØVRIG FJELLREV',
        location: {
            address: 'Reigstadvegen 111',
            postalCode: '5281',
            city: 'VALESTRANDSFOSSEN',
            municipal: 'OSTERØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '315495814',
        name: 'ELEGANT OPPFYLLENDE FJELLREV',
        location: {
            address: 'Seiersten Sentrum 1',
            postalCode: '1443',
            city: 'DRØBAK',
            municipal: 'FROGN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315785723',
        name: 'SPESIFIKK ENTUSIASTISK KATT GRØT',
        location: {
            address: 'Nedre Skalstadvei 57',
            postalCode: '3340',
            city: 'ÅMOT',
            municipal: 'MODUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '314787145',
        name: 'UNDERLIG FUNKSJONELL TIGER AS',
        location: {
            address: 'Nygårdsbakken 11C',
            postalCode: '4100',
            city: 'JØRPELAND',
            municipal: 'STRAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '315154006',
        name: 'GLUPSK SUBJEKTIV FJELLREV',
        location: {
            address: 'Hollenderåsen 2B',
            postalCode: '3234',
            city: 'SANDEFJORD',
            municipal: 'SANDEFJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '311872907',
        name: 'SUBJEKTIV ALMINNELIG FJELLREV',
        location: {
            address: 'Sønsterødveien 282',
            postalCode: '1591',
            city: 'SPERREBOTN',
            municipal: 'VÅLER',
            country: 'Norge',
        },
    },
    {
        orgnr: '311932748',
        name: 'KJÆRLIG ELASTISK TIGER AS',
        location: {
            address: 'Høgda 6',
            postalCode: '1820',
            city: 'SPYDEBERG',
            municipal: 'INDRE ØSTFOLD',
            country: 'Norge',
        },
    },
    {
        orgnr: '211974982',
        name: 'ENGASJERT TAUS TIGER AS',
        location: {
            address: 'Nordborgvegen 6',
            postalCode: '2413',
            city: 'ELVERUM',
            municipal: 'ELVERUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '315876036',
        name: 'INITIATIVRIK HELLIG TIGER AS',
        location: {
            address: 'Glimmerveien 1',
            postalCode: '4823',
            city: 'NEDENES',
            municipal: 'ARENDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '311362674',
        name: 'ALLMEKTIG TILLITSFULL TIGER AS',
        location: {
            address: 'Hestekleiva 9',
            postalCode: '1350',
            city: 'LOMMEDALEN',
            municipal: 'BÆRUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '311847988',
        name: 'VERTIKAL UMUSIKALSK FJELLREV',
        location: {
            address: 'Enerveien 12B',
            postalCode: '1570',
            city: 'DILLING',
            municipal: 'MOSS',
            country: 'Norge',
        },
    },
    {
        orgnr: '312142635',
        name: 'UEMOSJONELL SPRUDLENDE FJELLREV',
        location: {
            address: 'Vøienlinna 23',
            postalCode: '2750',
            city: 'GRAN',
            municipal: 'GRAN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315768128',
        name: 'TREG INTEGRERT TIGER AS',
        location: {
            address: 'Vestaveien 57B',
            postalCode: '1476',
            city: 'RASTA',
            municipal: 'LØRENSKOG',
            country: 'Norge',
        },
    },
    {
        orgnr: '311217119',
        name: 'MOBIL ROMANTISK TIGER AS',
        location: {
            address: 'Elvenesveien 13',
            postalCode: '1666',
            city: 'ROLVSØY',
            municipal: 'FREDRIKSTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '315063884',
        name: 'SNAR SPENNENDE FJELLREV',
        location: {
            address: 'Tårnsteinen 6',
            postalCode: '6783',
            city: 'STRYN',
            municipal: 'STRYN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315833353',
        name: 'VARM USENSUELL TIGER AS',
        location: {
            address: 'Busterudkleiva 54',
            postalCode: '1782',
            city: 'HALDEN',
            municipal: 'HALDEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315406811',
        name: 'SVENSK ALTERNATIV APE',
        location: {
            address: 'c/o Smul Akkord',
            postalCode: '1387',
            city: 'ASKER',
            municipal: 'ASKER',
            country: 'Norge',
        },
    },
    {
        orgnr: '311613855',
        name: 'ULIK FANTASIFULL TIGER AS',
        location: {
            address: 'Øvre Kongsbrekkene 18',
            postalCode: '5174',
            city: 'MATHOPEN',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314637100',
        name: 'DYREBAR LOGISK FJELLREV',
        location: {
            address: 'Viktor Baumanns vei 32C',
            postalCode: '7020',
            city: 'TRONDHEIM',
            municipal: 'TRONDHEIM',
            country: 'Norge',
        },
    },
    {
        orgnr: '311641190',
        name: 'REAL FESTLIG FJELLREV',
        location: {
            address: 'Torsnesveien 18',
            postalCode: '1630',
            city: 'GAMLE FREDRIKSTAD',
            municipal: 'FREDRIKSTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '315159369',
        name: 'ORDENTLIG VÅRLIG FJELLREV',
        location: {
            address: 'Søndre Moenplassen',
            postalCode: '5548',
            city: 'FEØY',
            municipal: 'KARMØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '311911538',
        name: 'OVEREKSPONERT ULYDIG TIGER AS',
        location: {
            address: 'Damgata 52',
            postalCode: '3179',
            city: 'ÅSGÅRDSTRAND',
            municipal: 'HORTEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '215342492',
        name: 'LYSEBLÅ SUBTIL TIGER AS',
        location: {
            address: 'Gimleveien 40',
            postalCode: '4630',
            city: 'KRISTIANSAND S',
            municipal: 'KRISTIANSAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '314846133',
        name: 'GLAD RYDDIG FJELLREV',
        location: {
            address: 'Ingelsrudvegen 488',
            postalCode: '2232',
            city: 'TOBØL',
            municipal: 'EIDSKOG',
            country: 'Norge',
        },
    },
    {
        orgnr: '311242857',
        name: 'OFFISIELL FESTLIG TIGER AS',
        location: {
            address: 'v/ Åpen Romantisk Fjernsyn',
            postalCode: '1719',
            city: 'GREÅKER',
            municipal: 'SARPSBORG',
            country: 'Norge',
        },
    },
    {
        orgnr: '314882679',
        name: 'RIKTIG RU KATT BU',
        location: {
            address: 'Hanalia 6',
            postalCode: '4328',
            city: 'SANDNES',
            municipal: 'SANDNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '215279022',
        name: 'BEGEISTRET MISFORNØYD FJELLREV',
        location: {
            address: 'Tveteneveien 94',
            postalCode: '3265',
            city: 'LARVIK',
            municipal: 'LARVIK',
            country: 'Norge',
        },
    },
    {
        orgnr: '315901871',
        name: 'REFLEKSIV MINKENDE TIGER AS',
        location: {
            address: 'Ingebret Andersens vei 3J',
            postalCode: '0955',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '211954752',
        name: 'NYTTIG OMTENKSOM TIGER AS',
        location: {
            address: 'Hognesaunvegen 48',
            postalCode: '7513',
            city: 'STJØRDAL',
            municipal: 'STJØRDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '315841437',
        name: 'SAKTE LEI TIGER AS',
        location: {
            address: 'Østre Slettenvika',
            postalCode: '9389',
            city: 'HUSØY I SENJA',
            municipal: 'SENJA',
            country: 'Norge',
        },
    },
    {
        orgnr: '314479130',
        name: 'KREATIV SKRAVLETE TIGER AS',
        location: {
            address: 'Øvre Bakklandet 36',
            postalCode: '7016',
            city: 'TRONDHEIM',
            municipal: 'TRONDHEIM',
            country: 'Norge',
        },
    },
    {
        orgnr: '311627007',
        name: 'OMTENKSOM FORETAKSOM FJELLREV',
        location: {
            address: 'v/ Neste Overnaturlig Dokumentar',
            postalCode: '0170',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '311330349',
        name: 'ORDKNAPP UNGT TIGER AS',
        location: {
            address: 'Søndre Bekken',
            postalCode: '0863',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314458478',
        name: 'TILLITSFULL INTERESSANT TIGER AS',
        location: {
            address: "Rosenkrantz' gate 9",
            postalCode: '4010',
            city: 'STAVANGER',
            municipal: 'STAVANGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '311578472',
        name: 'HARDHUDET HELDIG TIGER AS',
        location: {
            address: 'Reppevegen 6G',
            postalCode: '7054',
            city: 'RANHEIM',
            municipal: 'TRONDHEIM',
            country: 'Norge',
        },
    },
    {
        orgnr: '315379148',
        name: 'VÅRLIG UINTERESSERT TIGER AS',
        location: {
            address: 'Krosseveien 13',
            postalCode: '4617',
            city: 'KRISTIANSAND S',
            municipal: 'KRISTIANSAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '314855043',
        name: 'RYDDIG SENSITIV KATT REKKEFØLGE',
        location: {
            address: 'Okstaddalvegen 59',
            postalCode: '7711',
            city: 'STEINKJER',
            municipal: 'STEINKJER',
            country: 'Norge',
        },
    },
    {
        orgnr: '312132370',
        name: 'HÅNDFAST FREIDIG TIGER AS',
        location: {
            address: 'c/o Intrikat Fjernkontrollabbedisse',
            postalCode: '2340',
            city: 'LØTEN',
            municipal: 'LØTEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314975812',
        name: 'UTGÅTT SPESIFIKK FJELLREV',
        location: {
            address: 'Østbygdaveien 12',
            postalCode: '3074',
            city: 'SANDE I VESTFOLD',
            municipal: 'HOLMESTRAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '311846116',
        name: 'FANTASTISK TYPISK FJELLREV',
        location: {
            address: 'Nordre Bakkenjordstykket',
            postalCode: '5444',
            city: 'ESPEVÆR',
            municipal: 'BØMLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '315636264',
        name: 'KREATIV PUNKTLIG TIGER AS',
        location: {
            address: 'Kong Øysteins vei 266',
            postalCode: '7318',
            city: 'AGDENES',
            municipal: 'ORKLAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '314528018',
        name: 'SUBJEKTIV SELVTILFREDS FJELLREV',
        location: {
            address: '',
            postalCode: '7255',
            city: 'SUNDLANDET',
            municipal: 'ORKLAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '315403413',
        name: 'UFRUKTBAR NATURSTRIDIG TIGER AS',
        location: {
            address: 'Th. Kittelsens vei 7C',
            postalCode: '0377',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314568990',
        name: 'ELEKTRONISK BESTEMT TIGER AS',
        location: {
            address: 'Nordre Vollen',
            postalCode: '8766',
            city: 'LURØY',
            municipal: 'LURØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '311607855',
        name: 'ROBUST FILOSOFISK TIGER AS',
        location: {
            address: 'Ribstonveien 43E',
            postalCode: '0586',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '315380537',
        name: 'HELLIG REKTANGULÆR FJELLREV',
        location: {
            address: 'Peravegen 16',
            postalCode: '5218',
            city: 'NORDSTRØNO',
            municipal: 'BJØRNAFJORDEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314622898',
        name: 'AKSELERERENDE KJÆRLIG FJELLREV',
        location: {
            address: 'Manstadfaret 6B',
            postalCode: '1626',
            city: 'MANSTAD',
            municipal: 'FREDRIKSTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '311837915',
        name: 'RETT LYKKELIG FJELLREV',
        location: {
            address: '',
            postalCode: '8646',
            city: 'KORGEN',
            municipal: 'HEMNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '311397923',
        name: 'IDIOTSIKKER OPPRETT TIGER AS',
        location: {
            address: 'Dullumsvegen 44',
            postalCode: '7509',
            city: 'STJØRDAL',
            municipal: 'STJØRDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '214823772',
        name: 'LYS UKJENT TIGER AS',
        location: {
            address: 'Tromøyveien 6',
            postalCode: '4841',
            city: 'ARENDAL',
            municipal: 'ARENDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '315070775',
        name: 'USENSUELL HEL TIGER AS',
        location: {
            address: 'Plantefeltetødemarka',
            postalCode: '5021',
            city: 'BERGEN',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '311630253',
        name: 'LILLA MISFORNØYD TIGER AS',
        location: {
            address: 'Radøyvegen 2170',
            postalCode: '5936',
            city: 'MANGER',
            municipal: 'ALVER',
            country: 'Norge',
        },
    },
    {
        orgnr: '314902408',
        name: 'TILLITSFULL INKLUDERENDE KATT GEOGRAFI',
        location: {
            address: 'v/ Vidsynt Tomatbagasje',
            postalCode: '9300',
            city: 'FINNSNES',
            municipal: 'SENJA',
            country: 'Norge',
        },
    },
    {
        orgnr: '215667162',
        name: 'OPTIMISTISK GØYAL TIGER AS',
        location: {
            address: 'Nordre Grunnen',
            postalCode: '3511',
            city: 'HØNEFOSS',
            municipal: 'RINGERIKE',
            country: 'Norge',
        },
    },
    {
        orgnr: '311265997',
        name: 'ULASTELIG MODERNE TIGER AS',
        location: {
            address: 'Leknesveien 133',
            postalCode: '7994',
            city: 'LEKA',
            municipal: 'LEKA',
            country: 'Norge',
        },
    },
    {
        orgnr: '315560438',
        name: 'KJÆRLIG VÅRLIG FJELLREV',
        location: {
            address: 'Nansens vei 17',
            postalCode: '3260',
            city: 'LARVIK',
            municipal: 'LARVIK',
            country: 'Norge',
        },
    },
    {
        orgnr: '312063646',
        name: 'ALDRENDE OFFISIELL TIGER AS',
        location: {
            address: 'Vardesvingen 28',
            postalCode: '5141',
            city: 'FYLLINGSDALEN',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314417135',
        name: 'VIDSYNT SIKKER FJELLREV',
        location: {
            address: 'Utleirvegen 3A',
            postalCode: '7035',
            city: 'TRONDHEIM',
            municipal: 'TRONDHEIM',
            country: 'Norge',
        },
    },
    {
        orgnr: '315922097',
        name: 'KOMPLISERT LENGRE TIGER AS',
        location: {
            address: 'Jørgen B. Lysholms vei 67D',
            postalCode: '7041',
            city: 'TRONDHEIM',
            municipal: 'TRONDHEIM',
            country: 'Norge',
        },
    },
    {
        orgnr: '311299492',
        name: 'STYRBAR UTÅLMODIG FJELLREV',
        location: {
            address: 'Holmane 46',
            postalCode: '4364',
            city: 'SIREVÅG',
            municipal: 'HÅ',
            country: 'Norge',
        },
    },
    {
        orgnr: '312002426',
        name: 'KREATIV RU FJELLREV',
        location: {
            address: 'Bjellandsvegen 27',
            postalCode: '5550',
            city: 'SVEIO',
            municipal: 'SVEIO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314997220',
        name: 'SOSIAL EGOISTISK FJELLREV',
        location: {
            address: 'Thorsøveien 93',
            postalCode: '1634',
            city: 'GAMLE FREDRIKSTAD',
            municipal: 'FREDRIKSTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '315624916',
        name: 'LØSNINGSORIENTERT UTNYTTENDE FJELLREV',
        location: {
            address: 'Skogveien 39',
            postalCode: '9403',
            city: 'HARSTAD',
            municipal: 'HARSTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '311360477',
        name: 'UKLAR KOMPLISERT TIGER AS',
        location: {
            address: 'Steinvågvegen 67',
            postalCode: '6005',
            city: 'ÅLESUND',
            municipal: 'ÅLESUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '311433342',
        name: 'KUNSTIG STADIG FJELLREV',
        location: {
            address: 'Elvevegen 1',
            postalCode: '7670',
            city: 'INDERØY',
            municipal: 'INDERØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '211533102',
        name: 'VENSTRE SMUL FJELLREV',
        location: {
            address: 'Nedre Utsiktspunktetutkanten',
            postalCode: '8770',
            city: 'TRÆNA',
            municipal: 'TRÆNA',
            country: 'Norge',
        },
    },
    {
        orgnr: '315463300',
        name: 'KONKRET UKLAR FJELLREV',
        location: {
            address: 'Sofus Madsens vei 3',
            postalCode: '5097',
            city: 'BERGEN',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '215022242',
        name: 'FASCINERENDE KLARTENKT TIGER AS',
        location: {
            address: 'Østigardsveien 82',
            postalCode: '7530',
            city: 'MERÅKER',
            municipal: 'MERÅKER',
            country: 'Norge',
        },
    },
    {
        orgnr: '311644092',
        name: 'RYDDIG UPOPULÆR TIGER AS',
        location: {
            address: 'Bråtveitvegen 969',
            postalCode: '4244',
            city: 'NESFLATEN',
            municipal: 'SULDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '315690684',
        name: 'URETTFERDIG UTØRST TIGER AS',
        location: {
            address: 'Ekebergveien 292U',
            postalCode: '1166',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314895568',
        name: 'AKROBATISK VRIEN TIGER AS',
        location: {
            address: 'Skrevegen 132',
            postalCode: '5541',
            city: 'KOLNES',
            municipal: 'KARMØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '315197368',
        name: 'DYPSINDIG ÅPEN TIGER AS',
        location: {
            address: 'Trondheimsvegen 513',
            postalCode: '2092',
            city: 'MINNESUND',
            municipal: 'EIDSVOLL',
            country: 'Norge',
        },
    },
    {
        orgnr: '315032024',
        name: 'LEGITIM SAMLET FJELLREV',
        location: {
            address: 'Ravnsborgveien 43',
            postalCode: '1395',
            city: 'HVALSTAD',
            municipal: 'ASKER',
            country: 'Norge',
        },
    },
    {
        orgnr: '315918995',
        name: 'PERSONLIG INITIATIVRIK FJELLREV',
        location: {
            address: 'v/ Nyraffinert Fattigmann',
            postalCode: '5135',
            city: 'FLAKTVEIT',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '312360217',
        name: 'HÅNDFAST UTØRST TIGER AS',
        location: {
            address: 'Plassbakken 29',
            postalCode: '2760',
            city: 'BRANDBU',
            municipal: 'GRAN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314505557',
        name: 'FARLIG SALT TIGER AS',
        location: {
            address: 'Hagatjernveien 241',
            postalCode: '3050',
            city: 'MJØNDALEN',
            municipal: 'DRAMMEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315396654',
        name: 'LITT INTUITIV FJELLREV',
        location: {
            address: 'Mefjordveien 1435',
            postalCode: '9386',
            city: 'SENJAHOPEN',
            municipal: 'SENJA',
            country: 'Norge',
        },
    },
    {
        orgnr: '315426839',
        name: 'ORDINÆR DJERV TIGER AS',
        location: {
            address: 'Hanøyvegen 485',
            postalCode: '5310',
            city: 'HAUGLANDSHELLA',
            municipal: 'ASKØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '311347411',
        name: 'EVENTYRLIG UFORNUFTIG FJELLREV',
        location: {
            address: 'Leitetunet 17',
            postalCode: '8009',
            city: 'BODØ',
            municipal: 'BODØ',
            country: 'Norge',
        },
    },
    {
        orgnr: '315012325',
        name: 'SOFISTIKERT HENSIKTSMESSIG KATT FLAGGERMUS',
        location: {
            address: 'Birkemoveien 154',
            postalCode: '4463',
            city: 'UALAND',
            municipal: 'LUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '315905761',
        name: 'POPULÆR UPERSONLIG TIGER AS',
        location: {
            address: 'Jupiterveien 15',
            postalCode: '0489',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314754069',
        name: 'TRU HALV TIGER AS',
        location: {
            address: 'v/ Ledende Frisk Kulturplante',
            postalCode: '0182',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314588037',
        name: 'MORSOM ORDENTLIG FJELLREV',
        location: {
            address: 'Østbøvegen 14',
            postalCode: '5585',
            city: 'SANDEID',
            municipal: 'VINDAFJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '314526252',
        name: 'UPOPULÆR GLUPSK FJELLREV',
        location: {
            address: 'Stemmelia 33',
            postalCode: '5223',
            city: 'NESTTUN',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315061032',
        name: 'GYLDEN UGLESETT KATT STASJONSVOGN',
        location: {
            address: 'Lia 160',
            postalCode: '4885',
            city: 'GRIMSTAD',
            municipal: 'GRIMSTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '311263781',
        name: 'REKTANGULÆR KOMFORTABEL KATT SOKK',
        location: {
            address: 'Tiriltunga 15',
            postalCode: '6518',
            city: 'KRISTIANSUND N',
            municipal: 'KRISTIANSUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '314519876',
        name: 'ROBUST FIKTIV TIGER AS',
        location: {
            address: 'Orklaveien 129',
            postalCode: '7335',
            city: 'JERPSTAD',
            municipal: 'ORKLAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '315501695',
        name: 'SOSIAL OVERMODIG FJELLREV',
        location: {
            address: 'Rugdevegen 31B',
            postalCode: '1929',
            city: 'AULI',
            municipal: 'NES',
            country: 'Norge',
        },
    },
    {
        orgnr: '314582675',
        name: 'SNILL OMKOMMEN FJELLREV',
        location: {
            address: 'Lægdesvingen 74C',
            postalCode: '5096',
            city: 'BERGEN',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '311574868',
        name: 'STERK TILGIVENDE TIGER AS',
        location: {
            address: 'Øvreid 20',
            postalCode: '4406',
            city: 'FLEKKEFJORD',
            municipal: 'FLEKKEFJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '311319213',
        name: 'INTUITIV RUND TIGER AS',
        location: {
            address: 'Lindeveien 30',
            postalCode: '4515',
            city: 'MANDAL',
            municipal: 'LINDESNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '314692799',
        name: 'KRY GJESTFRI FJELLREV',
        location: {
            address: 'Lindelia 47',
            postalCode: '1346',
            city: 'GJETTUM',
            municipal: 'BÆRUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '315749395',
        name: 'ANALYSERENDE TILFELDIG TIGER AS',
        location: {
            address: 'John Tanke Svilands vei 11',
            postalCode: '4337',
            city: 'SANDNES',
            municipal: 'SANDNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '311964739',
        name: 'MOMENTAN OPPRØMT FJELLREV',
        location: {
            address: 'Storelvdalsveien 4650',
            postalCode: '2480',
            city: 'KOPPANG',
            municipal: 'STOR-ELVDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '315297524',
        name: 'BRA FLINK TIGER AS',
        location: {
            address: 'Magnus Berrføtts veg 2D',
            postalCode: '7046',
            city: 'TRONDHEIM',
            municipal: 'TRONDHEIM',
            country: 'Norge',
        },
    },
    {
        orgnr: '314251466',
        name: 'TANKEFULL UGJENNOMSIKTIG FJELLREV',
        location: {
            address: 'Nedre Møllenberg gate 35B',
            postalCode: '7014',
            city: 'TRONDHEIM',
            municipal: 'TRONDHEIM',
            country: 'Norge',
        },
    },
    {
        orgnr: '314651308',
        name: 'VAKKER LYDIG FJELLREV',
        location: {
            address: 'Fjellprydveien 5',
            postalCode: '4072',
            city: 'RANDABERG',
            municipal: 'RANDABERG',
            country: 'Norge',
        },
    },
    {
        orgnr: '315321581',
        name: 'TILGIVENDE NÆR TIGER AS',
        location: {
            address: 'Nordre Toppen',
            postalCode: '3922',
            city: 'PORSGRUNN',
            municipal: 'PORSGRUNN',
            country: 'Norge',
        },
    },
    {
        orgnr: '312045206',
        name: 'EKSAKT GJESTFRI TIGER AS',
        location: {
            address: 'Odalsgata 21B',
            postalCode: '2003',
            city: 'LILLESTRØM',
            municipal: 'LILLESTRØM',
            country: 'Norge',
        },
    },
    {
        orgnr: '314603141',
        name: 'PRESENTABEL FAMILIÆR FJELLREV',
        location: {
            address: 'Trasoppterrassen 47',
            postalCode: '0672',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '312319454',
        name: 'NETT VISSEN TIGER AS',
        location: {
            address: 'v/ Melankolsk Sosial Anatomi',
            postalCode: '6508',
            city: 'KRISTIANSUND N',
            municipal: 'KRISTIANSUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '315067146',
        name: 'NONFIGURATIV OVERFLØDIG FJELLREV',
        location: {
            address: 'Wallemsvikveien 14',
            postalCode: '5165',
            city: 'LAKSEVÅG',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314985834',
        name: 'EKSAKT LEKKER TIGER AS',
        location: {
            address: 'Verkstadvegen 21',
            postalCode: '2665',
            city: 'LESJA',
            municipal: 'LESJA',
            country: 'Norge',
        },
    },
    {
        orgnr: '314462904',
        name: 'HELLIG OPTIMISTISK TIGER AS',
        location: {
            address: 'Butveitsveien 102',
            postalCode: '4528',
            city: 'KOLLUNGTVEIT',
            municipal: 'LYNGDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '314770420',
        name: 'RASTLØS OPPBLÅST KATT LEVEREGEL',
        location: {
            address: 'Åsbakken 2',
            postalCode: '1659',
            city: 'TORP',
            municipal: 'FREDRIKSTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '315265762',
        name: 'DEILIG OMTENKSOM TIGER AS',
        location: {
            address: 'Brattfossveien 112',
            postalCode: '1880',
            city: 'EIDSBERG',
            municipal: 'INDRE ØSTFOLD',
            country: 'Norge',
        },
    },
    {
        orgnr: '312002949',
        name: 'UTMERKET PÅTROPPENDE FJELLREV',
        location: {
            address: 'Finstadlia 23',
            postalCode: '1475',
            city: 'FINSTADJORDET',
            municipal: 'LØRENSKOG',
            country: 'Norge',
        },
    },
    {
        orgnr: '312121441',
        name: 'LAV ROBUST TIGER AS',
        location: {
            address: 'Lagårdsvegen 2',
            postalCode: '4362',
            city: 'VIGRESTAD',
            municipal: 'HÅ',
            country: 'Norge',
        },
    },
    {
        orgnr: '311482106',
        name: 'STILLE MATEMATISK TIGER AS',
        location: {
            address: 'Sædalssvingene 8',
            postalCode: '5099',
            city: 'BERGEN',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314588053',
        name: 'HENSYNSFULL SPISS FJELLREV',
        location: {
            address: 'Nedre Vatnetutsiktspunktet',
            postalCode: '4127',
            city: 'LYSEBOTN',
            municipal: 'SANDNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '314679857',
        name: 'STRENG ANALYSERENDE FJELLREV',
        location: {
            address: 'Indre Fjordbotnetnylandet',
            postalCode: '5560',
            city: 'NEDSTRAND',
            municipal: 'TYSVÆR',
            country: 'Norge',
        },
    },
    {
        orgnr: '215924122',
        name: 'SNAKKESALIG UROKKELIG TIGER AS',
        location: {
            address: 'Utmarkamyra',
            postalCode: '5548',
            city: 'FEØY',
            municipal: 'KARMØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '311374133',
        name: 'TOPP OVERFLØDIG FJELLREV',
        location: {
            address: 'Svelvikveien 969',
            postalCode: '3060',
            city: 'SVELVIK',
            municipal: 'DRAMMEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315375746',
        name: 'PEN GÅEN TIGER AS',
        location: {
            address: 'v/ Oksyðertringsped Leggpause',
            postalCode: '4534',
            city: 'MARNARDAL',
            municipal: 'LINDESNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '311958135',
        name: 'ALDRENDE ULYDIG FJELLREV',
        location: {
            address: 'Ursins veg 6',
            postalCode: '2066',
            city: 'JESSHEIM',
            municipal: 'ULLENSAKER',
            country: 'Norge',
        },
    },
    {
        orgnr: '315454913',
        name: 'ENTUSIASTISK ERFAREN FJELLREV',
        location: {
            address: '',
            postalCode: '6300',
            city: 'ÅNDALSNES',
            municipal: 'RAUMA',
            country: 'Norge',
        },
    },
    {
        orgnr: '311365541',
        name: 'HÅNDLAGET POPULÆR TIGER AS',
        location: {
            address: 'Postveien 3A',
            postalCode: '4044',
            city: 'HAFRSFJORD',
            municipal: 'STAVANGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '315002958',
        name: 'HYGGELIG KJEMPENDE TIGER AS',
        location: {
            address: 'Ytre Råkenleiren',
            postalCode: '3004',
            city: 'DRAMMEN',
            municipal: 'DRAMMEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '311655191',
        name: 'GJENNOMSIKTIG SELVHJULPEN FJELLREV',
        location: {
            address: 'Tormods vei 1A',
            postalCode: '1184',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '311615505',
        name: 'GØYAL GRATIS FJELLREV',
        location: {
            address: 'Solbakken 10',
            postalCode: '8516',
            city: 'NARVIK',
            municipal: 'NARVIK',
            country: 'Norge',
        },
    },
    {
        orgnr: '315731992',
        name: 'DYKTIG OBSERVANT APE',
        location: {
            address: 'Tranehaugen 70',
            postalCode: '5238',
            city: 'RÅDAL',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314604997',
        name: 'BLOMSTRETE FROM FJELLREV',
        location: {
            address: 'Borgundvegen 501',
            postalCode: '6015',
            city: 'ÅLESUND',
            municipal: 'ÅLESUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '311670433',
        name: 'TØRR SANNFERDIG FJELLREV',
        location: {
            address: 'Abels gate 44A',
            postalCode: '1533',
            city: 'MOSS',
            municipal: 'MOSS',
            country: 'Norge',
        },
    },
    {
        orgnr: '311999095',
        name: 'NYTTIG NATURSTRIDIG FJELLREV',
        location: {
            address: 'Ytternesset 250',
            postalCode: '7607',
            city: 'LEVANGER',
            municipal: 'LEVANGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '311534602',
        name: 'KNUSLETE BLAUT KATT MASKIN',
        location: {
            address: 'c/o Unyttigveldig Tragedie',
            postalCode: '5516',
            city: 'HAUGESUND',
            municipal: 'HAUGESUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '311842862',
        name: 'EVIG STRAFFET FJELLREV',
        location: {
            address: '',
            postalCode: '6967',
            city: 'HELLEVIK I FJALER',
            municipal: 'FJALER',
            country: 'Norge',
        },
    },
    {
        orgnr: '311314106',
        name: 'SJENERT ØKOLOGISK TIGER AS',
        location: {
            address: 'Buskskauen 27',
            postalCode: '3237',
            city: 'SANDEFJORD',
            municipal: 'SANDEFJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '312389185',
        name: 'OVEREKSPONERT ULOGISK TIGER AS',
        location: {
            address: 'Østre Berg 15',
            postalCode: '7050',
            city: 'TRONDHEIM',
            municipal: 'TRONDHEIM',
            country: 'Norge',
        },
    },
    {
        orgnr: '311432427',
        name: 'STILLE OPPKLARENDE FJELLREV',
        location: {
            address: 'Sødal terrasse 13C',
            postalCode: '4630',
            city: 'KRISTIANSAND S',
            municipal: 'KRISTIANSAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '311252615',
        name: 'KJÆR FREIDIG TIGER AS',
        location: {
            address: 'Husvikveien 167',
            postalCode: '3124',
            city: 'TØNSBERG',
            municipal: 'TØNSBERG',
            country: 'Norge',
        },
    },
    {
        orgnr: '312145677',
        name: 'ENKEL HÅRSÅR FJELLREV',
        location: {
            address: 'Fundingrudveien 152',
            postalCode: '1459',
            city: 'NESODDEN',
            municipal: 'NESODDEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '311921363',
        name: 'SITRONGUL MORSOM FJELLREV',
        location: {
            address: 'Vokterveien 25A',
            postalCode: '3218',
            city: 'SANDEFJORD',
            municipal: 'SANDEFJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '311628046',
        name: 'STYRBAR REN FJELLREV',
        location: {
            address: 'Indre Markenbråten',
            postalCode: '0037',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314649559',
        name: 'SPETTETE RØRETE FJELLREV',
        location: {
            address: 'Kornstien 49',
            postalCode: '1479',
            city: 'KURLAND',
            municipal: 'LØRENSKOG',
            country: 'Norge',
        },
    },
    {
        orgnr: '314876156',
        name: 'INNSIKTSFULL ULOGISK TIGER AS',
        location: {
            address: 'Nord-Fugløyveien 1138',
            postalCode: '9135',
            city: 'VANNVÅG',
            municipal: 'KARLSØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '311664913',
        name: 'UTGÅTT POPULÆR FJELLREV',
        location: {
            address: 'Nedre Gullhaug 18',
            postalCode: '1354',
            city: 'BÆRUMS VERK',
            municipal: 'BÆRUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '315076889',
        name: 'PÅLITELIG UNØYAKTIG TIGER AS',
        location: {
            address: '',
            postalCode: '9773',
            city: 'NERVEI',
            municipal: 'GAMVIK',
            country: 'Norge',
        },
    },
    {
        orgnr: '311968203',
        name: 'SALT SMIGRENDE FJELLREV',
        location: {
            address: '',
            postalCode: '2760',
            city: 'BRANDBU',
            municipal: 'GRAN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314561988',
        name: 'BEVISST PRATSOM FJELLREV',
        location: {
            address: 'Trollien 7',
            postalCode: '5101',
            city: 'EIDSVÅGNESET',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314578619',
        name: 'EVENTYRLIG HANDLEKRAFTIG FJELLREV',
        location: {
            address: 'Eikeleinstien 46',
            postalCode: '3472',
            city: 'BØDALEN',
            municipal: 'ASKER',
            country: 'Norge',
        },
    },
    {
        orgnr: '311683896',
        name: 'ORIENTAL UFØLSOM FJELLREV',
        location: {
            address: 'Østre Strømmenjordet',
            postalCode: '9670',
            city: 'TUFJORD',
            municipal: 'MÅSØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '314399811',
        name: 'LIVSGLAD DISKRET TIGER AS',
        location: {
            address: 'Venneslavegen 297',
            postalCode: '4700',
            city: 'VENNESLA',
            municipal: 'VENNESLA',
            country: 'Norge',
        },
    },
    {
        orgnr: '311855948',
        name: 'STORARTET ORANSJE FJELLREV',
        location: {
            address: 'Vikjavegen 281',
            postalCode: '5708',
            city: 'VOSS',
            municipal: 'VOSS',
            country: 'Norge',
        },
    },
    {
        orgnr: '315928583',
        name: 'RUND TILBAKEHOLDEN TIGER AS',
        location: {
            address: 'Oredalsveien 106B',
            postalCode: '1613',
            city: 'FREDRIKSTAD',
            municipal: 'FREDRIKSTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '311610872',
        name: 'TREG GÅEN TIGER AS',
        location: {
            address: 'Halvorsrødveien 59',
            postalCode: '1622',
            city: 'GRESSVIK',
            municipal: 'FREDRIKSTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '314579143',
        name: 'KLARTENKT KOMPATIBEL FJELLREV',
        location: {
            address: 'Vårlikroken 5',
            postalCode: '4016',
            city: 'STAVANGER',
            municipal: 'STAVANGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '311607073',
        name: 'FORNØYD SKEPTISK TIGER AS',
        location: {
            address: 'Svilandveien 92',
            postalCode: '4338',
            city: 'SANDNES',
            municipal: 'SANDNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '311391658',
        name: 'KURSIV LOJAL FJELLREV',
        location: {
            address: 'Brobekkveien 45',
            postalCode: '0598',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314977378',
        name: 'RAVGUL UKONTROVERSIELL TIGER AS',
        location: {
            address: 'Nordre Stedetgrenden',
            postalCode: '8320',
            city: 'SKROVA',
            municipal: 'VÅGAN',
            country: 'Norge',
        },
    },
    {
        orgnr: '214872692',
        name: 'NATURLIG RUSTEN TIGER AS',
        location: {
            address: 'Vinnavegen 149',
            postalCode: '7512',
            city: 'STJØRDAL',
            municipal: 'STJØRDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '314929446',
        name: 'UTROLIG TILLITSFULL TIGER AS',
        location: {
            address: 'Vetrlidsallmenningen 6',
            postalCode: '5003',
            city: 'BERGEN',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315503523',
        name: 'NYSGJERRIG KJÆR FJELLREV',
        location: {
            address: 'Nedre Strandenplatået',
            postalCode: '8764',
            city: 'LOVUND',
            municipal: 'LURØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '314583809',
        name: 'UTYDELIG TROVERDIG FJELLREV',
        location: {
            address: 'Hatlestrandsvegen 523',
            postalCode: '5635',
            city: 'HATLESTRAND',
            municipal: 'KVINNHERAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '311376535',
        name: 'LYSEGRØNN DISTINGVERT KATT ÅRSPLAN',
        location: {
            address: 'c/o Usensuell Skjønn Spenne',
            postalCode: '9303',
            city: 'SILSAND',
            municipal: 'SENJA',
            country: 'Norge',
        },
    },
    {
        orgnr: '312099683',
        name: 'PARAT SLAPP TIGER AS',
        location: {
            address: 'Prinsegata 2C',
            postalCode: '3256',
            city: 'LARVIK',
            municipal: 'LARVIK',
            country: 'Norge',
        },
    },
    {
        orgnr: '315660602',
        name: 'SAMLET KOMPLISERT TIGER AS',
        location: {
            address: 'Radøyvegen 3009',
            postalCode: '5939',
            city: 'SLETTA',
            municipal: 'ALVER',
            country: 'Norge',
        },
    },
    {
        orgnr: '314590244',
        name: 'PRIKKETE DJERV FJELLREV',
        location: {
            address: 'Seljevegen 819',
            postalCode: '6717',
            city: 'FLATRAKET',
            municipal: 'STAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '314628519',
        name: 'SLAPP HYGGELIG FJELLREV',
        location: {
            address: 'Kirkebyenga 41',
            postalCode: '2323',
            city: 'INGEBERG',
            municipal: 'HAMAR',
            country: 'Norge',
        },
    },
    {
        orgnr: '311497545',
        name: 'UROMANTISK LEI TIGER AS',
        location: {
            address: 'Fjerdingen 18',
            postalCode: '3050',
            city: 'MJØNDALEN',
            municipal: 'DRAMMEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315768020',
        name: 'HÅNDFAST RAKRYGGET TIGER AS',
        location: {
            address: '',
            postalCode: '5593',
            city: 'SKÅNEVIK',
            municipal: 'ETNE',
            country: 'Norge',
        },
    },
    {
        orgnr: '314567331',
        name: 'FIOLETT SIVILISERT FJELLREV',
        location: {
            address: '',
            postalCode: '6530',
            city: 'AVERØY',
            municipal: 'AVERØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '315560721',
        name: 'EKSTRA UNØYAKTIG TIGER AS',
        location: {
            address: 'Grefsenveien 6A',
            postalCode: '0482',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '315485908',
        name: 'FATTET STYRBAR TIGER AS',
        location: {
            address: 'Klokkerveien 54',
            postalCode: '8074',
            city: 'BODØ',
            municipal: 'BODØ',
            country: 'Norge',
        },
    },
    {
        orgnr: '315217342',
        name: 'SITRONGUL POSSESSIV TIGER AS',
        location: {
            address: 'Håndverkeren 7',
            postalCode: '8250',
            city: 'ROGNAN',
            municipal: 'SALTDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '315829712',
        name: 'RIK PARAT TIGER AS',
        location: {
            address: 'Erling Skjalgssons gate 28B',
            postalCode: '0267',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '315399084',
        name: 'OPPLYST KANTETE TIGER AS',
        location: {
            address: 'Ingalia 6',
            postalCode: '6016',
            city: 'ÅLESUND',
            municipal: 'ÅLESUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '314909658',
        name: 'UTHOLDEN KUNST FJELLREV',
        location: {
            address: 'Skogbrynet 17',
            postalCode: '1513',
            city: 'MOSS',
            municipal: 'MOSS',
            country: 'Norge',
        },
    },
    {
        orgnr: '315294908',
        name: 'IHERDIG MODERNE TIGER AS',
        location: {
            address: 'Sunnivas vei 11C',
            postalCode: '4633',
            city: 'KRISTIANSAND S',
            municipal: 'KRISTIANSAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '315652731',
        name: 'VILJESTERK STRIDLYNT TIGER AS',
        location: {
            address: 'Målsnesveien 646',
            postalCode: '9321',
            city: 'MOEN',
            municipal: 'MÅLSELV',
            country: 'Norge',
        },
    },
    {
        orgnr: '311246704',
        name: 'SJELDEN AKVATISK KATT BUSSTOPP',
        location: {
            address: 'Solvangen 98',
            postalCode: '2013',
            city: 'SKJETTEN',
            municipal: 'LILLESTRØM',
            country: 'Norge',
        },
    },
    {
        orgnr: '311962671',
        name: 'MINKENDE MELANKOLSK TIGER AS',
        location: {
            address: 'v/ Påtroppende Pusekatt',
            postalCode: '2212',
            city: 'KONGSVINGER',
            municipal: 'KONGSVINGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '315172756',
        name: 'INTRIKAT DISKRET KATT ASTERISK',
        location: {
            address: 'Dramstadåsen 34',
            postalCode: '1812',
            city: 'ASKIM',
            municipal: 'INDRE ØSTFOLD',
            country: 'Norge',
        },
    },
    {
        orgnr: '211374292',
        name: 'FREIDIG VELKOMMEN FJELLREV',
        location: {
            address: 'Monrad Johansens vei 21',
            postalCode: '1410',
            city: 'KOLBOTN',
            municipal: 'NORDRE FOLLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '212305782',
        name: 'DOBBEL SPENNENDE FJELLREV',
        location: {
            address: 'Grensefaret 1C',
            postalCode: '1341',
            city: 'SLEPENDEN',
            municipal: 'BÆRUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '314861981',
        name: 'UNDERLIG KUL FJELLREV',
        location: {
            address: 'Nøtteveien 65',
            postalCode: '1715',
            city: 'YVEN',
            municipal: 'SARPSBORG',
            country: 'Norge',
        },
    },
    {
        orgnr: '315207010',
        name: 'AKTIV ANSVARSFULL FJELLREV',
        location: {
            address: 'Ytre Engenkollen',
            postalCode: '5075',
            city: 'BERGEN',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '311215930',
        name: 'PERFEKT MUNTER TIGER AS',
        location: {
            address: 'Trollveien 15E',
            postalCode: '1535',
            city: 'MOSS',
            municipal: 'MOSS',
            country: 'Norge',
        },
    },
    {
        orgnr: '315774918',
        name: 'FATTET FANTASILØS ISBJØRN SA',
        location: {
            address: '',
            postalCode: '7882',
            city: 'NORDLI',
            municipal: 'LIERNE',
            country: 'Norge',
        },
    },
    {
        orgnr: '315649684',
        name: 'POPULÆR RELEVANT TIGER AS',
        location: {
            address: 'v/ Kvadratisk Vertikal Suppôrter',
            postalCode: '2020',
            city: 'SKEDSMOKORSET',
            municipal: 'LILLESTRØM',
            country: 'Norge',
        },
    },
    {
        orgnr: '315493684',
        name: 'KOGNITIV SPENNENDE FJELLREV',
        location: {
            address: 'Vales veg 28',
            postalCode: '9019',
            city: 'TROMSØ',
            municipal: 'TROMSØ',
            country: 'Norge',
        },
    },
    {
        orgnr: '311229850',
        name: 'TRÅDLØS USYMMETRISK TIGER AS',
        location: {
            address: 'Agmund Bolts vei 7',
            postalCode: '0664',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314633059',
        name: 'OPPRØMT ULYDIG FJELLREV',
        location: {
            address: 'Torvmarkene 5',
            postalCode: '5302',
            city: 'STRUSSHAMN',
            municipal: 'ASKØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '311629859',
        name: 'GRÅ AKTVERDIG STRUTS LTD',
        location: {
            address: 'Rogstadvegen 11',
            postalCode: '2022',
            city: 'GJERDRUM',
            municipal: 'GJERDRUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '311498746',
        name: 'FULLKOMMEN LEDENDE FJELLREV',
        location: {
            address: 'Kronprinsens gate 2A',
            postalCode: '1606',
            city: 'FREDRIKSTAD',
            municipal: 'FREDRIKSTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '314723120',
        name: 'KVART ØVRIG APE',
        location: {
            address: 'Markvegen 30',
            postalCode: '2840',
            city: 'REINSVOLL',
            municipal: 'VESTRE TOTEN',
            country: 'Norge',
        },
    },
];

export default devVirksomheter;
