import { Arbeidsgiverforslag } from '../opprett-ny-stilling/VelgArbeidsgiver';

const devVirksomheter: Arbeidsgiverforslag[] = [
    {
        orgnr: '314743229',
        name: 'FAMILIÆR LYKKELIG TIGER AS',
        location: {
            address: 'Haakon VIIs gate 9',
            postalCode: '4005',
            city: 'STAVANGER',
            municipal: 'STAVANGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '311325914',
        name: 'URIMELIG DJERV KATT ODDE',
        location: {
            address: 'Sleipneveien 65B',
            postalCode: '3274',
            city: 'LARVIK',
            municipal: 'LARVIK',
            country: 'Norge',
        },
    },
    {
        orgnr: '314699246',
        name: 'KREATIV TILGIVENDE FJELLREV',
        location: {
            address: 'Heggelibakken 23B',
            postalCode: '0375',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '311214810',
        name: 'RU UTÅLMODIG TIGER AS',
        location: {
            address: 'Vendomveien 2',
            postalCode: '1165',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '311536176',
        name: 'ULASTELIG LANG TIGER AS',
        location: {
            address: 'Per Lykkes veg 1',
            postalCode: '7022',
            city: 'TRONDHEIM',
            municipal: 'TRONDHEIM',
            country: 'Norge',
        },
    },
    {
        orgnr: '311614967',
        name: 'KUNNSKAPSRIK RAKRYGGET TIGER AS',
        location: {
            address: 'Paal Bergs vei 89',
            postalCode: '0692',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '215539032',
        name: 'MOSEGRODD UFORGJENGELIG FJELLREV',
        location: {
            address: '',
            postalCode: '7336',
            city: 'MELDAL',
            municipal: 'ORKLAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '314902904',
        name: 'LYSELILLA KULTURELL FJELLREV',
        location: {
            address: 'Martavegen 14A',
            postalCode: '6013',
            city: 'ÅLESUND',
            municipal: 'ÅLESUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '311641360',
        name: 'PERFEKT NONFIGURATIV TIGER AS',
        location: {
            address: 'Malerhaugveien 11',
            postalCode: '0661',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '214805642',
        name: 'STOLT FAMØS TIGER AS',
        location: {
            address: 'Snømusstien 1',
            postalCode: '9512',
            city: 'ALTA',
            municipal: 'ALTA',
            country: 'Norge',
        },
    },
    {
        orgnr: '315278201',
        name: 'KVADRATISK KONSENTRISK FJELLREV',
        location: {
            address: 'Søndre Øyalia',
            postalCode: '8865',
            city: 'TRO',
            municipal: 'ALSTAHAUG',
            country: 'Norge',
        },
    },
    {
        orgnr: '314532848',
        name: 'BLØT AUTORISERT FJELLREV',
        location: {
            address: 'Søndre Platåetdyngen',
            postalCode: '4863',
            city: 'NELAUG',
            municipal: 'ÅMLI',
            country: 'Norge',
        },
    },
    {
        orgnr: '314789806',
        name: 'JURIDISK STA FJELLREV',
        location: {
            address: 'Henrik Angells gate 1A',
            postalCode: '7045',
            city: 'TRONDHEIM',
            municipal: 'TRONDHEIM',
            country: 'Norge',
        },
    },
    {
        orgnr: '314783107',
        name: 'INKONSEKVENT RAVGUL FJELLREV',
        location: {
            address: 'Skogveien 64A',
            postalCode: '1368',
            city: 'STABEKK',
            municipal: 'BÆRUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '314786319',
        name: 'NORMAL EVIG TIGER AS',
        location: {
            address: 'Sandveien 56',
            postalCode: '8324',
            city: 'DIGERMULEN',
            municipal: 'VÅGAN',
            country: 'Norge',
        },
    },
    {
        orgnr: '311924176',
        name: 'AKVATISK KONKRET KATT NISSE',
        location: {
            address: 'Hagegata 36C',
            postalCode: '0653',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314631293',
        name: 'KONSENTRISK SELVTILFREDS FJELLREV',
        location: {
            address: '',
            postalCode: '2260',
            city: 'KIRKENÆR',
            municipal: 'GRUE',
            country: 'Norge',
        },
    },
    {
        orgnr: '312128713',
        name: 'VERD EKSEMPLARISK TIGER AS',
        location: {
            address: 'Merslandsveien 976',
            postalCode: '4534',
            city: 'MARNARDAL',
            municipal: 'LINDESNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '315778182',
        name: 'SAMTIDIG MEMORERENDE TIGER AS',
        location: {
            address: 'Krosseveien 17',
            postalCode: '4617',
            city: 'KRISTIANSAND S',
            municipal: 'KRISTIANSAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '314585895',
        name: 'HEMMELIGHETSFULL SNILL FJELLREV',
        location: {
            address: 'Indre Liatjernet',
            postalCode: '9650',
            city: 'AKKARFJORD',
            municipal: 'HAMMERFEST',
            country: 'Norge',
        },
    },
    {
        orgnr: '315356555',
        name: 'UTYDELIG LUN APE',
        location: {
            address: 'c/o Sigen Hes Frynse',
            postalCode: '1481',
            city: 'HAGAN',
            municipal: 'NITTEDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '315465966',
        name: 'FLYKTIG FARLIG TIGER AS',
        location: {
            address: 'Vestre Røinevei 10',
            postalCode: '3410',
            city: 'SYLLING',
            municipal: 'LIER',
            country: 'Norge',
        },
    },
    {
        orgnr: '214562642',
        name: 'INTERESSERT PATENT FJELLREV',
        location: {
            address: 'Bjørnestien 10',
            postalCode: '3188',
            city: 'HORTEN',
            municipal: 'HORTEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314857259',
        name: 'UTNYTTENDE AKVATISK TIGER AS',
        location: {
            address: 'Lillemyrveien 16',
            postalCode: '4632',
            city: 'KRISTIANSAND S',
            municipal: 'KRISTIANSAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '315478766',
        name: 'FAMILIÆR STRIDLYNT FJELLREV',
        location: {
            address: 'Nestunveien 29',
            postalCode: '4026',
            city: 'STAVANGER',
            municipal: 'STAVANGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '315896045',
        name: 'GØYAL SIGEN FJELLREV',
        location: {
            address: 'Døblebakken 7B',
            postalCode: '4700',
            city: 'VENNESLA',
            municipal: 'VENNESLA',
            country: 'Norge',
        },
    },
    {
        orgnr: '214627272',
        name: 'KLOK KJENT FJELLREV',
        location: {
            address: 'Ytre Røysenråken',
            postalCode: '6483',
            city: 'ONA',
            municipal: 'ÅLESUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '311596810',
        name: 'DIVERSE ÅPEN TIGER AS',
        location: {
            address: 'Sverdrups gate 48',
            postalCode: '4007',
            city: 'STAVANGER',
            municipal: 'STAVANGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '315339200',
        name: 'FILOSOFISK LYSTIG KATT INFEKSJON',
        location: {
            address: 'Østre Kysten',
            postalCode: '3741',
            city: 'SKIEN',
            municipal: 'SKIEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315845815',
        name: 'SMISKENDE DOGMATISK FJELLREV',
        location: {
            address: 'Ekebergveien 123',
            postalCode: '1912',
            city: 'ENEBAKK',
            municipal: 'ENEBAKK',
            country: 'Norge',
        },
    },
    {
        orgnr: '311371770',
        name: 'AKSELERERENDE KONSENTRISK TIGER AS',
        location: {
            address: 'Kalfarveien 78C',
            postalCode: '5022',
            city: 'BERGEN',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '311328840',
        name: 'KLASSISK TYKKHUDET KATT HANDELSMANN',
        location: {
            address: 'Straumelien 15',
            postalCode: '5151',
            city: 'STRAUMSGREND',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '215525902',
        name: 'SNAR SJOKKERT ISBJØRN SA',
        location: {
            address: 'Hølandsveien 180B',
            postalCode: '1903',
            city: 'GAN',
            municipal: 'LILLESTRØM',
            country: 'Norge',
        },
    },
    {
        orgnr: '314763637',
        name: 'INKONSEKVENT KRITISK KATT MOSKUS',
        location: {
            address: 'Ytre Åkeren',
            postalCode: '2170',
            city: 'FENSTAD',
            municipal: 'NES',
            country: 'Norge',
        },
    },
    {
        orgnr: '215384462',
        name: 'ULASTELIG FRISK KATT HUMOR',
        location: {
            address: 'Silogata 5 A',
            postalCode: '2850',
            city: 'LENA',
            municipal: 'ØSTRE TOTEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315610400',
        name: 'NATURSTRIDIG RING APE',
        location: {
            address: 'Klovamyrsvegen 22',
            postalCode: '5420',
            city: 'RUBBESTADNESET',
            municipal: 'BØMLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '311452894',
        name: 'UTSTRAKT ELEGANT TIGER AS',
        location: {
            address: 'Johanna Schwarz vei 2A',
            postalCode: '3610',
            city: 'KONGSBERG',
            municipal: 'KONGSBERG',
            country: 'Norge',
        },
    },
    {
        orgnr: '314458680',
        name: 'OPERATIV RETT TIGER AS',
        location: {
            address: 'Linesettet 21',
            postalCode: '8373',
            city: 'BALLSTAD',
            municipal: 'VESTVÅGØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '315194776',
        name: 'STA TREG TIGER AS',
        location: {
            address: 'Skeievegen 37',
            postalCode: '5585',
            city: 'SANDEID',
            municipal: 'VINDAFJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '311356372',
        name: 'KUNSTIG EMPATISK TIGER AS',
        location: {
            address: 'Skullerudveien 36B',
            postalCode: '0694',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '215869792',
        name: 'INNSIKTSFULL USELVSTENDIG KATT RYNKE',
        location: {
            address: 'Iddefjordsveien 892',
            postalCode: '1765',
            city: 'HALDEN',
            municipal: 'HALDEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '311239392',
        name: 'PRATSOM PARAT TIGER AS',
        location: {
            address: 'Øverveien 297',
            postalCode: '7288',
            city: 'SOKNEDAL',
            municipal: 'MIDTRE GAULDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '315586003',
        name: 'UTROLIG UGLESETT TIGER AS',
        location: {
            address: 'Sørheia 19',
            postalCode: '4640',
            city: 'SØGNE',
            municipal: 'KRISTIANSAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '212141402',
        name: 'UNGT ROMANTISK PUMA',
        location: {
            address: 'Leirenlandstedet',
            postalCode: '5021',
            city: 'BERGEN',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315509637',
        name: 'BARMHJERTIG PUSLETE TIGER AS',
        location: {
            address: 'Svendsemarka 20',
            postalCode: '3409',
            city: 'TRANBY',
            municipal: 'LIER',
            country: 'Norge',
        },
    },
    {
        orgnr: '314856457',
        name: 'MATT UTTRYKKSFULL TIGER AS',
        location: {
            address: 'Sanglundvegen 4A',
            postalCode: '2319',
            city: 'HAMAR',
            municipal: 'HAMAR',
            country: 'Norge',
        },
    },
    {
        orgnr: '312005727',
        name: 'IVRIG TRÅDLØS TIGER AS',
        location: {
            address: 'Sentervollen 18',
            postalCode: '4347',
            city: 'LYE',
            municipal: 'TIME',
            country: 'Norge',
        },
    },
    {
        orgnr: '314888480',
        name: 'VAKKER JUSTERBAR TIGER AS',
        location: {
            address: 'Sildreveien 2',
            postalCode: '9516',
            city: 'ALTA',
            municipal: 'ALTA',
            country: 'Norge',
        },
    },
    {
        orgnr: '314640748',
        name: 'FASCINERENDE HARDHUDET FJELLREV',
        location: {
            address: 'Bakkegata 6',
            postalCode: '3405',
            city: 'LIER',
            municipal: 'LIER',
            country: 'Norge',
        },
    },
    {
        orgnr: '214525712',
        name: 'HURTIG ALVORLIG FJELLREV',
        location: {
            address: 'Kirkerudveien 17',
            postalCode: '3470',
            city: 'SLEMMESTAD',
            municipal: 'ASKER',
            country: 'Norge',
        },
    },
    {
        orgnr: '315081491',
        name: 'KANTETE AKTVERDIG FJELLREV',
        location: {
            address: 'Bromstadekra 45C',
            postalCode: '7046',
            city: 'TRONDHEIM',
            municipal: 'TRONDHEIM',
            country: 'Norge',
        },
    },
    {
        orgnr: '311390767',
        name: 'ROBUST TRU TIGER AS',
        location: {
            address: 'Per Sivles vei 4B',
            postalCode: '1511',
            city: 'MOSS',
            municipal: 'MOSS',
            country: 'Norge',
        },
    },
    {
        orgnr: '314463447',
        name: 'BLID SITRONGUL TIGER AS',
        location: {
            address: '',
            postalCode: '5627',
            city: 'JONDAL',
            municipal: 'ULLENSVANG',
            country: 'Norge',
        },
    },
    {
        orgnr: '314698797',
        name: 'ØVRIG BETYDELIG FJELLREV',
        location: {
            address: 'Aklandsveien 1503',
            postalCode: '4994',
            city: 'AKLAND',
            municipal: 'RISØR',
            country: 'Norge',
        },
    },
    {
        orgnr: '311417932',
        name: 'MUSKULØS KORREKT FJELLREV',
        location: {
            address: 'Sandnesvegen 170',
            postalCode: '7940',
            city: 'OTTERSØY',
            municipal: 'NÆRØYSUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '315887593',
        name: 'OVERNATURLIG LATTERMILD TIGER AS',
        location: {
            address: 'Solstrandvegen 520',
            postalCode: '9020',
            city: 'TROMSDALEN',
            municipal: 'TROMSØ',
            country: 'Norge',
        },
    },
    {
        orgnr: '314805445',
        name: 'TYDELIG UPRESIS FJELLREV',
        location: {
            address: 'Rektorhaugen 9B',
            postalCode: '0876',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314800230',
        name: 'FREIDIG DRIFTIG FJELLREV',
        location: {
            address: 'Nymansveien 122',
            postalCode: '4015',
            city: 'STAVANGER',
            municipal: 'STAVANGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '311417894',
        name: 'VAKKER PRIKKETE FJELLREV',
        location: {
            address: 'Nesleveien 5',
            postalCode: '3360',
            city: 'GEITHUS',
            municipal: 'MODUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '315203147',
        name: 'ELEGANT FORNØYD TIGER AS',
        location: {
            address: 'Bjørgavegen 181',
            postalCode: '5709',
            city: 'VOSS',
            municipal: 'VOSS',
            country: 'Norge',
        },
    },
    {
        orgnr: '314905733',
        name: 'FAMILIÆR DYR FJELLREV',
        location: {
            address: 'Eikeheiveien 20',
            postalCode: '4640',
            city: 'SØGNE',
            municipal: 'KRISTIANSAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '314924568',
        name: 'ENKEL OPPLAGT FJELLREV',
        location: {
            address: 'Torehaugen 5',
            postalCode: '5382',
            city: 'SKOGSVÅG',
            municipal: 'ØYGARDEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315577292',
        name: 'VOKSENDE DYPSINDIG HEST BORETTSLAG',
        location: {
            address: 'Traneveien 8A',
            postalCode: '4318',
            city: 'SANDNES',
            municipal: 'SANDNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '314911385',
        name: 'BLAUT SPISS FJELLREV',
        location: {
            address: 'Glitterudveien 42',
            postalCode: '1352',
            city: 'KOLSÅS',
            municipal: 'BÆRUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '215760952',
        name: 'ANSTENDIG VOKAL FJELLREV',
        location: {
            address: 'Biørnsborgbakken 22',
            postalCode: '3770',
            city: 'KRAGERØ',
            municipal: 'KRAGERØ',
            country: 'Norge',
        },
    },
    {
        orgnr: '314624009',
        name: 'VERTIKAL FILOSOFISK FJELLREV',
        location: {
            address: 'Stensmyrveien 6B',
            postalCode: '3050',
            city: 'MJØNDALEN',
            municipal: 'DRAMMEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314705696',
        name: 'KVART PATENT FJELLREV',
        location: {
            address: 'Havevegen 4C',
            postalCode: '3725',
            city: 'SKIEN',
            municipal: 'SKIEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315183081',
        name: 'USYMMETRISK MUSIKALSK FJELLREV',
        location: {
            address: 'Håbafjellveien 58',
            postalCode: '4325',
            city: 'SANDNES',
            municipal: 'SANDNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '311842528',
        name: 'FANTASILØS MUSKULØS FJELLREV',
        location: {
            address: 'Fjellvegen 63',
            postalCode: '8664',
            city: 'MOSJØEN',
            municipal: 'VEFSN',
            country: 'Norge',
        },
    },
    {
        orgnr: '312102668',
        name: 'PRESIS USIKKER TIGER AS',
        location: {
            address: 'Hiltonveien 13A',
            postalCode: '1341',
            city: 'SLEPENDEN',
            municipal: 'BÆRUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '311841432',
        name: 'UMAKE OPPBLÅST FJELLREV',
        location: {
            address: 'Bøveien 63',
            postalCode: '4071',
            city: 'RANDABERG',
            municipal: 'RANDABERG',
            country: 'Norge',
        },
    },
    {
        orgnr: '315865743',
        name: 'LIVLIG UEMOSJONELL TIGER AS',
        location: {
            address: '',
            postalCode: '7517',
            city: 'HELL',
            municipal: 'STJØRDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '311946315',
        name: 'KUL RASTLØS FJELLREV',
        location: {
            address: '',
            postalCode: '2690',
            city: 'SKJÅK',
            municipal: 'SKJÅK',
            country: 'Norge',
        },
    },
    {
        orgnr: '315573750',
        name: 'USELVSTENDIG FORSKJELLIG FJELLREV',
        location: {
            address: 'Bromstadvegen 18B',
            postalCode: '7045',
            city: 'TRONDHEIM',
            municipal: 'TRONDHEIM',
            country: 'Norge',
        },
    },
    {
        orgnr: '315239079',
        name: 'EFFEKTIV VÅRLIG TIGER AS',
        location: {
            address: 'Indre Berget',
            postalCode: '4656',
            city: 'HAMRESANDEN',
            municipal: 'KRISTIANSAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '311378325',
        name: 'GNIEN GLUPSK KATT FIOLIN',
        location: {
            address: 'Innmarkasundet',
            postalCode: '5582',
            city: 'ØLENSVÅG',
            municipal: 'VINDAFJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '311286757',
        name: 'PUSLETE SNAKKESALIG TIGER AS',
        location: {
            address: 'Magna Ottersens vei 7',
            postalCode: '3070',
            city: 'SANDE I VESTFOLD',
            municipal: 'HOLMESTRAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '312089246',
        name: 'MOTLØS POPULÆR TIGER AS',
        location: {
            address: 'Traneveien 20',
            postalCode: '4049',
            city: 'HAFRSFJORD',
            municipal: 'STAVANGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '311386271',
        name: 'BETYDELIG ARITMETISK TIGER AS',
        location: {
            address: 'Taugbølvegen 16',
            postalCode: '2114',
            city: 'DISENÅ',
            municipal: 'SØR-ODAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '311289365',
        name: 'STRAFFET BERØMT TIGER AS',
        location: {
            address: 'Gamle Maridalsvei 45',
            postalCode: '0890',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '315918022',
        name: 'MOBIL BLAUT TIGER AS',
        location: {
            address: 'Langbrygga 10',
            postalCode: '3724',
            city: 'SKIEN',
            municipal: 'SKIEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315440440',
        name: 'AKSEPTABEL KONKRET TIGER AS',
        location: {
            address: 'Østskaugen 13',
            postalCode: '3624',
            city: 'LYNGDAL I NUMEDAL',
            municipal: 'FLESBERG',
            country: 'Norge',
        },
    },
    {
        orgnr: '314647971',
        name: 'SPED SJENERT FJELLREV',
        location: {
            address: 'Korsbergsvegen 578',
            postalCode: '2420',
            city: 'TRYSIL',
            municipal: 'TRYSIL',
            country: 'Norge',
        },
    },
    {
        orgnr: '311607634',
        name: 'LANG SART TIGER AS',
        location: {
            address: 'Fanakrå 31',
            postalCode: '5244',
            city: 'FANA',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '312380099',
        name: 'KONKURRANSEDYKTIG POSITIV HUND DA',
        location: {
            address: 'Rudolf Nilsens veg 19',
            postalCode: '2407',
            city: 'ELVERUM',
            municipal: 'ELVERUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '314621344',
        name: 'OKSYDERT ØKOLOGISK FJELLREV',
        location: {
            address: 'Breistølen 23',
            postalCode: '5034',
            city: 'BERGEN',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314637224',
        name: 'JORDISK TOPP FJELLREV',
        location: {
            address: 'Østre Skogenåsen',
            postalCode: '5547',
            city: 'UTSIRA',
            municipal: 'UTSIRA',
            country: 'Norge',
        },
    },
    {
        orgnr: '314717457',
        name: 'SNÅL FJONG FJELLREV',
        location: {
            address: 'Skolevegen 3',
            postalCode: '2879',
            city: 'ODNES',
            municipal: 'SØNDRE LAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '314493532',
        name: 'FLEKSIBEL ØVRIG TIGER AS',
        location: {
            address: 'Langøyveien 62',
            postalCode: '1679',
            city: 'KRÅKERØY',
            municipal: 'FREDRIKSTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '311628356',
        name: 'DYPSINDIG EMPATISK TIGER AS',
        location: {
            address: 'Leiteveien 27',
            postalCode: '4312',
            city: 'SANDNES',
            municipal: 'SANDNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '314610075',
        name: 'PÅLITELIG ULIK FJELLREV',
        location: {
            address: 'Ekebergveien 5C',
            postalCode: '0192',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314538501',
        name: 'SALT HISTORISK FJELLREV',
        location: {
            address: 'Alvevegen 115',
            postalCode: '9016',
            city: 'TROMSØ',
            municipal: 'TROMSØ',
            country: 'Norge',
        },
    },
    {
        orgnr: '311662325',
        name: 'FERSK HELDIG FJELLREV',
        location: {
            address: 'Midtvardhaugane 19',
            postalCode: '5314',
            city: 'KJERRGARDEN',
            municipal: 'ASKØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '314863208',
        name: 'FATTIG STA TIGER AS',
        location: {
            address: 'Professor Dahls gate 48',
            postalCode: '0260',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '311349236',
        name: 'VISSEN TREKANTET TIGER AS',
        location: {
            address: 'Torneveien 3',
            postalCode: '3320',
            city: 'VESTFOSSEN',
            municipal: 'ØVRE EIKER',
            country: 'Norge',
        },
    },
    {
        orgnr: '211578602',
        name: 'ALLMEKTIG ROMANTISK KATT EKORNHALE',
        location: {
            address: 'Vestre Ødemarkafastlandet',
            postalCode: '4233',
            city: 'ERFJORD',
            municipal: 'SULDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '315717981',
        name: 'MORALSK PUNKTLIG APE',
        location: {
            address: 'Stedjeåsen 39A',
            postalCode: '6856',
            city: 'SOGNDAL',
            municipal: 'SOGNDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '311468464',
        name: 'FORSTÅELSESFULL FALSK TIGER AS',
        location: {
            address: 'Øvre Lia',
            postalCode: '6213',
            city: 'TAFJORD',
            municipal: 'FJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '315183529',
        name: 'FYSISK MEDGJØRLIG FJELLREV',
        location: {
            address: 'Vestre Ødemarkaosen',
            postalCode: '4182',
            city: 'SKARTVEIT',
            municipal: 'STAVANGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '315423945',
        name: 'PLEIENDE UNDERLIG TIGER AS',
        location: {
            address: 'Dagalistien 20',
            postalCode: '0776',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '311639447',
        name: 'SYMPATISK KLARTENKT STRUTS LTD',
        location: {
            address: 'Nedre Kulås vei 2',
            postalCode: '1724',
            city: 'SARPSBORG',
            municipal: 'SARPSBORG',
            country: 'Norge',
        },
    },
    {
        orgnr: '311401432',
        name: 'LEDENDE LYSEBLÅ HAMSTER KF',
        location: {
            address: 'Ravnåsveien 40B',
            postalCode: '1254',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '214590212',
        name: 'SPETTETE FALSK FJELLREV',
        location: {
            address: 'Indre Innmarkaåkeren',
            postalCode: '4233',
            city: 'ERFJORD',
            municipal: 'SULDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '211912022',
        name: 'KOMISK KURSIV FJELLREV',
        location: {
            address: 'Nils Hansens vei 25',
            postalCode: '0667',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '311613898',
        name: 'TREIG SKAPENDE TIGER AS',
        location: {
            address: 'Nordre Kneiken',
            postalCode: '8198',
            city: 'NORDNESØY',
            municipal: 'RØDØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '311847996',
        name: 'MOTLØS BEMERKELSESVERDIG FJELLREV',
        location: {
            address: 'v/ Troverdig Tillitsfull Parfyme',
            postalCode: '8430',
            city: 'MYRE',
            municipal: 'ØKSNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '312121646',
        name: 'FIRKANTET TOÅRIG TIGER AS',
        location: {
            address: 'Bognesvegen 8',
            postalCode: '6016',
            city: 'ÅLESUND',
            municipal: 'ÅLESUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '314852095',
        name: 'PÅLITELIG LEI KATT NATURRESSURS',
        location: {
            address: 'Lykkjavegen 66',
            postalCode: '3560',
            city: 'HEMSEDAL',
            municipal: 'HEMSEDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '315665361',
        name: 'SNILL PUNKTLIG TIGER AS',
        location: {
            address: 'Verket 77',
            postalCode: '2580',
            city: 'FOLLDAL',
            municipal: 'FOLLDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '315056837',
        name: 'FORMBAR VERD FJELLREV',
        location: {
            address: 'Goppollvegen 8',
            postalCode: '2634',
            city: 'FÅVANG',
            municipal: 'RINGEBU',
            country: 'Norge',
        },
    },
    {
        orgnr: '314709357',
        name: 'AKUSTISK PESSIMISTISK FJELLREV',
        location: {
            address: 'Gauselvågen 17',
            postalCode: '4032',
            city: 'STAVANGER',
            municipal: 'STAVANGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '314638417',
        name: 'PUNKTLIG ØKOLOGISK PIGGSVIN',
        location: {
            address: 'Nedre Fjorden',
            postalCode: '4334',
            city: 'ÅLGÅRD',
            municipal: 'GJESDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '311210947',
        name: 'PRESENTABEL URIMELIG TIGER AS',
        location: {
            address: 'Søndre Lia',
            postalCode: '9011',
            city: 'TROMSØ',
            municipal: 'TROMSØ',
            country: 'Norge',
        },
    },
    {
        orgnr: '314693337',
        name: 'TRYGG INTERESSANT FJELLREV',
        location: {
            address: 'Strandpromenaden 5',
            postalCode: '3370',
            city: 'VIKERSUND',
            municipal: 'MODUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '311858769',
        name: 'UFRUKTBAR PLUTSELIG TIGER AS',
        location: {
            address: 'Strandgaten 2',
            postalCode: '4550',
            city: 'FARSUND',
            municipal: 'FARSUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '311907654',
        name: 'HÅNDLAGET KOSTBAR FJELLREV',
        location: {
            address: 'Postsvingen 10B',
            postalCode: '3031',
            city: 'DRAMMEN',
            municipal: 'DRAMMEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '311919601',
        name: 'KOMPATIBEL GILD FJELLREV',
        location: {
            address: 'Dillingveien 29',
            postalCode: '1570',
            city: 'DILLING',
            municipal: 'MOSS',
            country: 'Norge',
        },
    },
    {
        orgnr: '314699300',
        name: 'MODERNE OPPRETTHOLDENDE FJELLREV',
        location: {
            address: 'Kvilten sør 9',
            postalCode: '2443',
            city: 'DREVSJØ',
            municipal: 'ENGERDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '314760212',
        name: 'SLEM RU KROKODILLE',
        location: {
            address: 'Øvre Innlandethøyden',
            postalCode: '4182',
            city: 'SKARTVEIT',
            municipal: 'STAVANGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '311882368',
        name: 'UFORNUFTIG FALSK GAUPE',
        location: {
            address: 'Ytre Krokenfjorden',
            postalCode: '3595',
            city: 'HAUGASTØL',
            municipal: 'HOL',
            country: 'Norge',
        },
    },
    {
        orgnr: '315781485',
        name: 'OKSYDERT RAVGUL TIGER AS',
        location: {
            address: 'Leirfjordveien 260',
            postalCode: '8264',
            city: 'ENGAN',
            municipal: 'SØRFOLD',
            country: 'Norge',
        },
    },
    {
        orgnr: '311660144',
        name: 'MANGE MATT FJELLREV',
        location: {
            address: 'Soltunveien 37',
            postalCode: '9322',
            city: 'KARLSTAD',
            municipal: 'MÅLSELV',
            country: 'Norge',
        },
    },
    {
        orgnr: '311986007',
        name: 'MATEMATISK AKTPÅGIVENDE FJELLREV',
        location: {
            address: 'Tokkevegen 2A',
            postalCode: '3733',
            city: 'SKIEN',
            municipal: 'SKIEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315423287',
        name: 'LEI FILOSOFISK TIGER AS',
        location: {
            address: 'Gamleveien 83',
            postalCode: '4315',
            city: 'SANDNES',
            municipal: 'SANDNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '314824237',
        name: 'DIREKTE LEKKER ISBJØRN SA',
        location: {
            address: 'Åsveien 91',
            postalCode: '7530',
            city: 'MERÅKER',
            municipal: 'MERÅKER',
            country: 'Norge',
        },
    },
    {
        orgnr: '314658310',
        name: 'ELEGANT HEL FJELLREV',
        location: {
            address: 'Osbakkvegen 74',
            postalCode: '7540',
            city: 'KLÆBU',
            municipal: 'TRONDHEIM',
            country: 'Norge',
        },
    },
    {
        orgnr: '311672517',
        name: 'FORNØYD DYPSINDIG FJELLREV',
        location: {
            address: 'Søndre Kneikenelva',
            postalCode: '9770',
            city: 'MEHAMN',
            municipal: 'GAMVIK',
            country: 'Norge',
        },
    },
    {
        orgnr: '311448048',
        name: 'SKRAVLETE NONFIGURATIV FJELLREV',
        location: {
            address: 'Eikeliveien 21',
            postalCode: '1555',
            city: 'SON',
            municipal: 'VESTBY',
            country: 'Norge',
        },
    },
    {
        orgnr: '211430052',
        name: 'REALISTISK LYSEBLÅ FJELLREV',
        location: {
            address: 'Rosselandsvegen 77',
            postalCode: '4647',
            city: 'BRENNÅSEN',
            municipal: 'KRISTIANSAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '314803388',
        name: 'KURSIV BRA KATT GORILLA',
        location: {
            address: 'v/ Nett Vifte',
            postalCode: '2770',
            city: 'JAREN',
            municipal: 'GRAN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315868343',
        name: 'UTROLIG UVANLIG TIGER AS',
        location: {
            address: 'Endrestøveien 6',
            postalCode: '4073',
            city: 'RANDABERG',
            municipal: 'RANDABERG',
            country: 'Norge',
        },
    },
    {
        orgnr: '312142376',
        name: 'TRYGG KUL FJELLREV',
        location: {
            address: 'Vikersundveien 402',
            postalCode: '3533',
            city: 'TYRISTRAND',
            municipal: 'RINGERIKE',
            country: 'Norge',
        },
    },
    {
        orgnr: '315041422',
        name: 'UNDERDANIG KRITISK TIGER AS',
        location: {
            address: 'v/ Famøs Opprømt Brudekjolekant',
            postalCode: '2613',
            city: 'LILLEHAMMER',
            municipal: 'LILLEHAMMER',
            country: 'Norge',
        },
    },
    {
        orgnr: '314624874',
        name: 'OPPJAGET TOPP FJELLREV',
        location: {
            address: 'Nordøyveien 13',
            postalCode: '8909',
            city: 'BRØNNØYSUND',
            municipal: 'BRØNNØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '314746201',
        name: 'SELVTILFREDS EKSTRA SKILPADDE BA',
        location: {
            address: 'Lensmann Haaversens vei 120',
            postalCode: '2019',
            city: 'SKEDSMOKORSET',
            municipal: 'LILLESTRØM',
            country: 'Norge',
        },
    },
    {
        orgnr: '315126649',
        name: 'VISSEN ULLEN TIGER AS',
        location: {
            address: 'Levretoppen 3',
            postalCode: '1346',
            city: 'GJETTUM',
            municipal: 'BÆRUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '314446453',
        name: 'STORARTET SENTRAL TIGER AS',
        location: {
            address: 'Mikkelholmen 10',
            postalCode: '9514',
            city: 'ALTA',
            municipal: 'ALTA',
            country: 'Norge',
        },
    },
    {
        orgnr: '314446828',
        name: 'SLAPP OMKOMMEN KATT PÅSKE',
        location: {
            address: 'Hamnegata 7',
            postalCode: '9600',
            city: 'HAMMERFEST',
            municipal: 'HAMMERFEST',
            country: 'Norge',
        },
    },
    {
        orgnr: '315589835',
        name: 'OVERFLADISK SART KATT FYRSTE',
        location: {
            address: 'Vøyensvingen 10',
            postalCode: '0457',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314471083',
        name: 'AKSELERERENDE UPERSONLIG FJELLREV',
        location: {
            address: 'Skogbrynet 32',
            postalCode: '3032',
            city: 'DRAMMEN',
            municipal: 'DRAMMEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '312133598',
        name: 'SAMTIDIG ARITMETISK FJELLREV',
        location: {
            address: 'Kirkeveien 608',
            postalCode: '3143',
            city: 'KJØPMANNSKJÆR',
            municipal: 'FÆRDER',
            country: 'Norge',
        },
    },
    {
        orgnr: '315880815',
        name: 'UNDERLIG NETT TIGER AS',
        location: {
            address: 'Folke Bernadottes vei 31B',
            postalCode: '0862',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '315485673',
        name: 'MATEMATISK FORMBAR FJELLREV',
        location: {
            address: 'Spåkenesveien 440',
            postalCode: '9146',
            city: 'OLDERDALEN',
            municipal: 'KÅFJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '311622420',
        name: 'HENSYNSLØS LYS STRUTS LTD',
        location: {
            address: 'Varahollsvegen 58',
            postalCode: '2429',
            city: 'TØRBERGET',
            municipal: 'TRYSIL',
            country: 'Norge',
        },
    },
    {
        orgnr: '314673158',
        name: 'KVADRATISK GLEMSOM FJELLREV',
        location: {
            address: '',
            postalCode: '6094',
            city: 'LEINØY',
            municipal: 'HERØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '314655559',
        name: 'SNILL USJENERT FJELLREV',
        location: {
            address: 'Riis terrasse 24',
            postalCode: '2007',
            city: 'KJELLER',
            municipal: 'LILLESTRØM',
            country: 'Norge',
        },
    },
    {
        orgnr: '311222732',
        name: 'TAPPER HUSLØS TIGER AS',
        location: {
            address: 'Nedre Heiaøya',
            postalCode: '9742',
            city: 'KUNES',
            municipal: 'LEBESBY',
            country: 'Norge',
        },
    },
    {
        orgnr: '314974751',
        name: 'MUSKULØS SMART FJELLREV',
        location: {
            address: 'Universitetsgata 7',
            postalCode: '0164',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314448146',
        name: 'OPPSTEMT OFFISIELL TIGER AS',
        location: {
            address: 'Skogkanten 9B',
            postalCode: '1410',
            city: 'KOLBOTN',
            municipal: 'NORDRE FOLLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '215638472',
        name: 'PARISK FORNUFTIG FJELLREV',
        location: {
            address: 'v/ Selvhjulpentelefonkatalog',
            postalCode: '4529',
            city: 'BYREMO',
            municipal: 'LYNGDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '314674014',
        name: 'VIRTUELL UGJENNOMSIKTIG FJELLREV',
        location: {
            address: 'Østmo 2',
            postalCode: '3734',
            city: 'SKIEN',
            municipal: 'SKIEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '311642049',
        name: 'FREDELIG INTERESSERT TIGER AS',
        location: {
            address: 'Strandgata 26',
            postalCode: '8400',
            city: 'SORTLAND',
            municipal: 'SORTLAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '314642678',
        name: 'KUNNSKAPSRIK ANALYSERENDE FJELLREV',
        location: {
            address: 'Nordre Jordetutkanten',
            postalCode: '0026',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314629809',
        name: 'SAMTIDIG REKTANGULÆR FJELLREV',
        location: {
            address: 'Fjellveien 58',
            postalCode: '5019',
            city: 'BERGEN',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315509491',
        name: 'FLAT UBESTIKKELIG FJELLREV',
        location: {
            address: 'Gjerdesmutten 2A',
            postalCode: '0957',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '315360242',
        name: 'GUL GNIEN TIGER AS',
        location: {
            address: 'c/o Gåen Oppfyllende Hoppe',
            postalCode: '5118',
            city: 'ULSET',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314625064',
        name: 'BERØMT OPPBLÅST FJELLREV',
        location: {
            address: 'Nedre Krokendyngen',
            postalCode: '9770',
            city: 'MEHAMN',
            municipal: 'GAMVIK',
            country: 'Norge',
        },
    },
    {
        orgnr: '315511194',
        name: 'VÅKEN VELDIG ISBJØRN SA',
        location: {
            address: 'Korsvoll terrasse 19A',
            postalCode: '0881',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '314803795',
        name: 'TALEFØR AKVATISK FJELLREV',
        location: {
            address: 'Petterstien 10',
            postalCode: '1930',
            city: 'AURSKOG',
            municipal: 'AURSKOG-HØLAND',
            country: 'Norge',
        },
    },
    {
        orgnr: '211243872',
        name: 'EKSAKT VELDIG KATT OLDEMOR',
        location: {
            address: 'Gudrun Kolderups veg 1',
            postalCode: '5265',
            city: 'YTRE ARNA',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '314585453',
        name: 'ALVORLIG LYKKELIG FJELLREV',
        location: {
            address: 'Nedre Svingenhumpen',
            postalCode: '8880',
            city: 'BÆRØYVÅGEN',
            municipal: 'ALSTAHAUG',
            country: 'Norge',
        },
    },
    {
        orgnr: '214686902',
        name: 'EGOISTISK TOPP FJELLREV',
        location: {
            address: 'Sætherveien 201',
            postalCode: '1866',
            city: 'BÅSTAD',
            municipal: 'INDRE ØSTFOLD',
            country: 'Norge',
        },
    },
    {
        orgnr: '315132401',
        name: 'SITRONGUL JUSTERBAR TIGER AS',
        location: {
            address: 'Sømveien 24B',
            postalCode: '0493',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '311520334',
        name: 'OMSORGSFULL ELASTISK APE',
        location: {
            address: 'Skippergata 1A',
            postalCode: '6507',
            city: 'KRISTIANSUND N',
            municipal: 'KRISTIANSUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '214912732',
        name: 'KOMPLEKS UTSTRAKT FJELLREV',
        location: {
            address: 'Tønsvikvegen 237',
            postalCode: '9023',
            city: 'KROKELVDALEN',
            municipal: 'TROMSØ',
            country: 'Norge',
        },
    },
    {
        orgnr: '315292840',
        name: 'RUND HORISONTAL TIGER AS',
        location: {
            address: 'Furuveien 19',
            postalCode: '3178',
            city: 'VÅLE',
            municipal: 'TØNSBERG',
            country: 'Norge',
        },
    },
    {
        orgnr: '314666011',
        name: 'POSSESSIV FESTLIG FJELLREV',
        location: {
            address: 'Utøyvegen 480',
            postalCode: '7670',
            city: 'INDERØY',
            municipal: 'INDERØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '311259180',
        name: 'ORDINÆR SOLID FJELLREV',
        location: {
            address: 'Londalen 48',
            postalCode: '5267',
            city: 'ESPELAND',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '311401378',
        name: 'SAMARBEIDSVILLIG AKTVERDIG PIGGSVIN',
        location: {
            address: 'Beiteveien 2',
            postalCode: '1890',
            city: 'RAKKESTAD',
            municipal: 'RAKKESTAD',
            country: 'Norge',
        },
    },
    {
        orgnr: '312358220',
        name: 'AKSEPTABEL USENSUELL KATT HARPUN',
        location: {
            address: 'Dyrøya 3',
            postalCode: '6260',
            city: 'SKODJE',
            municipal: 'ÅLESUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '315456274',
        name: 'MÅTEHOLDEN UROKKELIG TIGER AS',
        location: {
            address: 'Mælumsgutua 1',
            postalCode: '2330',
            city: 'VALLSET',
            municipal: 'STANGE',
            country: 'Norge',
        },
    },
    {
        orgnr: '315088585',
        name: 'KONKURRANSEDYKTIG USTABIL APE',
        location: {
            address: 'v/ Tørr Bjørnunge',
            postalCode: '6418',
            city: 'SEKKEN',
            municipal: 'MOLDE',
            country: 'Norge',
        },
    },
    {
        orgnr: '314464273',
        name: 'TANKEFULL SVENSK TIGER AS',
        location: {
            address: 'Hekkveien 23',
            postalCode: '2450',
            city: 'RENA',
            municipal: 'ÅMOT',
            country: 'Norge',
        },
    },
    {
        orgnr: '312301466',
        name: 'OMKOMMEN TOPP FJELLREV',
        location: {
            address: 'Søndre Engennylandet',
            postalCode: '8764',
            city: 'LOVUND',
            municipal: 'LURØY',
            country: 'Norge',
        },
    },
    {
        orgnr: '315410002',
        name: 'OPPFYLLENDE ØDE TIGER AS',
        location: {
            address: 'v/ Eksplosiv Upersonlig Hjulvisp',
            postalCode: '0561',
            city: 'OSLO',
            municipal: 'OSLO',
            country: 'Norge',
        },
    },
    {
        orgnr: '311625144',
        name: 'DIREKTE GNIEN STRUTS LTD',
        location: {
            address: 'Tveiteveien 40',
            postalCode: '4849',
            city: 'ARENDAL',
            municipal: 'ARENDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '314648382',
        name: 'FERSK UPERSONLIG FJELLREV',
        location: {
            address: 'Nesevågen 19',
            postalCode: '5970',
            city: 'BYRKNESØY',
            municipal: 'GULEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315305837',
        name: 'KONSERVATIV UFRUKTBAR FJELLREV',
        location: {
            address: 'Vesthellinga 1',
            postalCode: '1923',
            city: 'SØRUM',
            municipal: 'LILLESTRØM',
            country: 'Norge',
        },
    },
    {
        orgnr: '315531160',
        name: 'SKJØR TROVERDIG KATT NITROGEN',
        location: {
            address: 'Kodalveien 1149',
            postalCode: '3158',
            city: 'ANDEBU',
            municipal: 'SANDEFJORD',
            country: 'Norge',
        },
    },
    {
        orgnr: '311625888',
        name: 'LETT VRIEN TIGER AS',
        location: {
            address: 'Øyaveien 9',
            postalCode: '3514',
            city: 'HØNEFOSS',
            municipal: 'RINGERIKE',
            country: 'Norge',
        },
    },
    {
        orgnr: '315664462',
        name: 'USYMMETRISK ALLSIDIG TIGER AS',
        location: {
            address: 'v/ Bevisst Moderne Kile',
            postalCode: '4016',
            city: 'STAVANGER',
            municipal: 'STAVANGER',
            country: 'Norge',
        },
    },
    {
        orgnr: '311920553',
        name: 'VÅKEN GRØNN TIGER AS',
        location: {
            address: 'Sagveien 7',
            postalCode: '1816',
            city: 'SKIPTVET',
            municipal: 'SKIPTVET',
            country: 'Norge',
        },
    },
    {
        orgnr: '315416949',
        name: 'KALD KRITISK ISBJØRN SA',
        location: {
            address: 'Harkmarksveien 931',
            postalCode: '4516',
            city: 'MANDAL',
            municipal: 'LINDESNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '314759532',
        name: 'REALISTISK ELASTISK TIGER AS',
        location: {
            address: 'Ortugrenden 56',
            postalCode: '5143',
            city: 'FYLLINGSDALEN',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '311986090',
        name: 'GRETTEN INITIATIVRIK FJELLREV',
        location: {
            address: 'Fürstveien 46',
            postalCode: '1367',
            city: 'SNARØYA',
            municipal: 'BÆRUM',
            country: 'Norge',
        },
    },
    {
        orgnr: '314873599',
        name: 'ANALYSERENDE USIKKER FJELLREV',
        location: {
            address: 'Hemsedalsvegen 3330',
            postalCode: '3560',
            city: 'HEMSEDAL',
            municipal: 'HEMSEDAL',
            country: 'Norge',
        },
    },
    {
        orgnr: '311995502',
        name: 'KOMPETENT FARLIG FJELLREV',
        location: {
            address: 'Søndre Plantefeltetstedet',
            postalCode: '3593',
            city: 'USTAOSET',
            municipal: 'HOL',
            country: 'Norge',
        },
    },
    {
        orgnr: '315918847',
        name: 'SMUL FAMØS TIGER AS',
        location: {
            address: 'Ringveien 17A',
            postalCode: '3050',
            city: 'MJØNDALEN',
            municipal: 'DRAMMEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315339073',
        name: 'FUNKSJONELL HARDHUDET TIGER AS',
        location: {
            address: 'Fossvegen 630',
            postalCode: '2330',
            city: 'VALLSET',
            municipal: 'STANGE',
            country: 'Norge',
        },
    },
    {
        orgnr: '311362429',
        name: 'TOPP HUSLØS TIGER AS',
        location: {
            address: 'Holalien 4A',
            postalCode: '5163',
            city: 'LAKSEVÅG',
            municipal: 'BERGEN',
            country: 'Norge',
        },
    },
    {
        orgnr: '315739896',
        name: 'UFUNKSJONELL LEDENDE KATT SAUDABU',
        location: {
            address: 'Tegnestiften 6',
            postalCode: '2821',
            city: 'GJØVIK',
            municipal: 'GJØVIK',
            country: 'Norge',
        },
    },
    {
        orgnr: '315548888',
        name: 'INNSIKTSFULL PLEIENDE TIGER AS',
        location: {
            address: 'Konsmoheiveien 646',
            postalCode: '4534',
            city: 'MARNARDAL',
            municipal: 'LINDESNES',
            country: 'Norge',
        },
    },
    {
        orgnr: '311877070',
        name: 'AKTIV TOM FJELLREV',
        location: {
            address: 'Bjerkøyveien 54',
            postalCode: '3133',
            city: 'DUKEN',
            municipal: 'FÆRDER',
            country: 'Norge',
        },
    },
    {
        orgnr: '314613767',
        name: 'BESKJEDEN AVANSERT FJELLREV',
        location: {
            address: 'Flaenveien 45',
            postalCode: '2015',
            city: 'LEIRSUND',
            municipal: 'LILLESTRØM',
            country: 'Norge',
        },
    },
    {
        orgnr: '312029383',
        name: 'URETTFERDIG RING FJELLREV',
        location: {
            address: 'Bjørkestubben 3',
            postalCode: '4351',
            city: 'KLEPPE',
            municipal: 'KLEPP',
            country: 'Norge',
        },
    },
    {
        orgnr: '315410347',
        name: 'LYSTIG POSITIV TIGER AS',
        location: {
            address: 'Hærnøsandveien 40B',
            postalCode: '6514',
            city: 'KRISTIANSUND N',
            municipal: 'KRISTIANSUND',
            country: 'Norge',
        },
    },
    {
        orgnr: '215391922',
        name: 'FIOLETT TAPPER HUND DA',
        location: {
            address: 'Nordre Bekken',
            postalCode: '1900',
            city: 'FETSUND',
            municipal: 'LILLESTRØM',
            country: 'Norge',
        },
    },
    {
        orgnr: '315470889',
        name: 'VEIK PLEIENDE HEST BORETTSLAG',
        location: {
            address: 'Vipevegen 5',
            postalCode: '3917',
            city: 'PORSGRUNN',
            municipal: 'PORSGRUNN',
            country: 'Norge',
        },
    },
    {
        orgnr: '312008475',
        name: 'UTAKKNEMLIG SOSIAL FJELLREV',
        location: {
            address: 'Hauglandsvegen 60',
            postalCode: '4346',
            city: 'BRYNE',
            municipal: 'TIME',
            country: 'Norge',
        },
    },
    {
        orgnr: '311448501',
        name: 'UKONTROVERSIELL UPOPULÆR TIGER AS',
        location: {
            address: 'Søndre Viddapletten',
            postalCode: '9580',
            city: 'BERGSFJORD',
            municipal: 'LOPPA',
            country: 'Norge',
        },
    },
];
export default devVirksomheter;
