/* eslint-disable */

export const AD_API = __STILLING_PAM_AD_API__;
export const LOGIN_URL = __STILLING_PAM_LOGIN_URL__;
export const SEARCH_API = __STILLING_PAM_SEARCH_API__;
export const KANDIDATLISTE_API = __STILLING_PAM_KANDIDATLISTE_API_URL__;
export const KANDIDATSOK_API = `${KANDIDATLISTE_API}/kandidatsok`;
export const REKRUTTERING_API = __STILLING_REKRUTTERING_API__;
export const REKRUTTERINGSBISTAND_BASE_URL = __STILLING_REKRUTTERINGSBISTAND_BASE_URL__;
export const VIS_STILLING_URL = __STILLING_VIS_STILLING_URL__;
